import { useCallback, useEffect, useRef, useState } from 'react'
import { ScoresheetApiError, scoresheetErrorMessage, type ScoresheetApi } from './scoresheetApi'
import type { ManagerReportingCycles, ScoresheetDetail, ScoresheetLedgerItem, ScoresheetSummary } from './types'

const signed = (amount: number) => amount >= 0 ? `+${amount} XP` : `−${Math.abs(amount)} XP`
const date = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
function State({ text, error, retry }: { text: string; error?: boolean; retry?: () => void }) { return <div className={`reporting-state${error ? ' reporting-state--error' : ''}`} role={error ? 'alert' : 'status'}><p>{text}</p>{retry && <button className="button button--quiet" type="button" onClick={retry}>Retry</button>}</div> }

export function ManagerScoresheet({ api }: { api: ScoresheetApi }) {
  const [cycles, setCycles] = useState<ManagerReportingCycles | null>(null)
  const [cycleId, setCycleId] = useState('')
  const [summary, setSummary] = useState<ScoresheetSummary | null>(null)
  const [loadingCycles, setLoadingCycles] = useState(true)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const summaryRequest = useRef(0)
  const activeCycle = useRef(cycleId)
  activeCycle.current = cycleId
  const loadCycles = useCallback(async () => { setLoadingCycles(true); setError(null); try { const result = await api.getReportingCycles(); setCycles(result); setCycleId((current) => result.cycles.some((cycle) => cycle.id === current) ? current : result.defaultCycleId ?? '') } catch (requestError) { setError(scoresheetErrorMessage(requestError)) } finally { setLoadingCycles(false) } }, [api])
  const loadSummary = useCallback(async () => { if (!cycleId) return; const request = ++summaryRequest.current; setLoading(true); setError(null); setSelectedId(null); try { const result = await api.getScoresheet(cycleId); if (request === summaryRequest.current) setSummary(result) } catch (requestError) { if (request === summaryRequest.current) setError(scoresheetErrorMessage(requestError)) } finally { if (request === summaryRequest.current) setLoading(false) } }, [api, cycleId])
  useEffect(() => { void loadCycles() }, [loadCycles])
  useEffect(() => { void loadSummary() }, [loadSummary])
  if (loadingCycles) return <State text="Loading manager reporting cycles…" />
  if (error && !cycles) return <State text={error} error retry={() => void loadCycles()} />
  if (!cycles?.cycles.length || !cycleId) return <State text="No reporting cycles are available for the Scoresheet." />
  const selectedCycle = cycles.cycles.find((cycle) => cycle.id === cycleId)!
  return <div className="reporting-area"><div className="cycle-context"><div><p className="eyebrow">MANAGER REPORTING</p><strong>{selectedCycle.name}</strong><span>Cycle selection changes this Scoresheet reporting context.</span></div><label><span>Reporting cycle</span><select aria-label="Scoresheet reporting cycle" value={cycleId} onChange={(event) => { setSelectedId(null); setCycleId(event.target.value) }}>{cycles.cycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{cycle.name} · {cycle.status}</option>)}</select></label></div>
    {loading ? <State text="Loading Scoresheet…" /> : error ? <State text={error} error retry={() => void loadSummary()} /> : !summary?.rows.length ? <State text="No participants are enrolled in this reporting cycle." /> : <section><header className="section-heading"><p className="eyebrow">APPEND-ONLY XP LEDGER</p><h2>Scoresheet summary</h2><p>All cycle participants are shown, including zero-XP and inactive roster entries.</p></header><div className="table-wrap"><table className="scoresheet-table"><thead><tr><th>Participant</th><th>Status</th><th>Task Approval XP</th><th>Manual Award XP</th><th>Raid XP</th><th>Adjustments</th><th>Total XP</th></tr></thead><tbody>{summary.rows.map((row) => <tr key={row.participantId}><td><button className="participant-link" type="button" onClick={() => setSelectedId(row.participantId)}>{row.displayName}</button></td><td><span className="participant-status">{row.participantStatus}</span></td><td>{row.bySource.taskApprovalXp}</td><td>{row.bySource.manualAwardXp}</td><td>{row.bySource.raidXp}</td><td className={row.byEntryType.netAdjustmentXp < 0 ? 'xp-negative' : ''}>{row.byEntryType.netAdjustmentXp}</td><td><strong>{row.totalXp}</strong></td></tr>)}</tbody></table></div></section>}
    {selectedId && <ParticipantDetail key={`${cycleId}:${selectedId}`} api={api} cycleId={cycleId} participantId={selectedId} onClose={() => setSelectedId(null)} refreshSummary={async () => { if (activeCycle.current !== cycleId) throw new Error('Reporting cycle changed.'); const request = ++summaryRequest.current; const result = await api.getScoresheet(cycleId); if (request !== summaryRequest.current || activeCycle.current !== cycleId) throw new Error('Reporting cycle changed.'); setSummary(result) }} />}
  </div>
}

function LedgerRows({ items, onCorrect }: { items: ScoresheetLedgerItem[]; onCorrect: (item: ScoresheetLedgerItem) => void }) { return <div className="activity-rows scoresheet-ledger">{items.map((item) => <article key={item.id}><strong className={item.amount < 0 ? 'xp-negative' : 'xp-positive'}>{signed(item.amount)}</strong><div><h3>{item.source.label}</h3><p>{item.entryType} · {item.sourceType}</p><p>{item.reason}</p><span>{date(item.awardedAt)}{item.reversesEntryId ? ` · Reverses ${item.reversesEntryId}` : ''}</span>{item.correction !== null && <button className="button button--quiet correction-trigger" type="button" onClick={() => onCorrect(item)}>Correct XP</button>}</div></article>)}</div> }

function ParticipantDetail({ api, cycleId, participantId, onClose, refreshSummary }: { api: ScoresheetApi; cycleId: string; participantId: string; onClose: () => void; refreshSummary: () => Promise<void> }) {
  const [detail, setDetail] = useState<ScoresheetDetail | null>(null); const [items, setItems] = useState<ScoresheetLedgerItem[]>([]); const [nextCursor, setNextCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState<string | null>(null); const [correcting, setCorrecting] = useState<ScoresheetLedgerItem | null>(null); const [success, setSuccess] = useState<string | null>(null)
  const load = useCallback(async (cursor?: string | null) => { cursor ? setLoadingMore(true) : setLoading(true); setError(null); try { const result = await api.getParticipant(participantId, cycleId, cursor); setDetail(result); setItems((current) => cursor ? [...current, ...result.items.filter((item) => !current.some((existing) => existing.id === item.id))] : result.items); setNextCursor(result.nextCursor) } catch (requestError) { setError(scoresheetErrorMessage(requestError)) } finally { setLoading(false); setLoadingMore(false) } }, [api, cycleId, participantId])
  const refreshDetail = useCallback(async () => { const result = await api.getParticipant(participantId, cycleId, null); setDetail(result); setItems(result.items); setNextCursor(result.nextCursor); return result }, [api, cycleId, participantId])
  const refreshConflictTarget = useCallback(async (entryId: string) => {
    const first = await api.getParticipant(participantId, cycleId, null); const refreshed = [...first.items]; let target = refreshed.find((item) => item.id === entryId); let cursor = first.nextCursor; const followed = new Set<string>()
    while (!target && cursor && !followed.has(cursor)) { followed.add(cursor); const page = await api.getParticipant(participantId, cycleId, cursor); for (const item of page.items) if (!refreshed.some((existing) => existing.id === item.id)) refreshed.push(item); target = refreshed.find((item) => item.id === entryId); cursor = page.nextCursor }
    setDetail(first); setItems(refreshed); setNextCursor(cursor)
    return target?.correction ? target : null
  }, [api, cycleId, participantId])
  useEffect(() => { void load(null) }, [load])
  return <section className="scoresheet-detail reporting-card" aria-label="Participant Scoresheet detail">{loading ? <State text="Loading participant ledger…" /> : error && !detail ? <State text={error} error retry={() => void load(null)} /> : detail && <><header className="detail-heading"><div><p className="eyebrow">PARTICIPANT DRILL-DOWN</p><h2>{detail.participant.displayName}</h2><span className="participant-status">{detail.participant.participantStatus}</span></div><button className="button button--quiet" type="button" onClick={onClose}>Close</button></header>{success && <div className="success-notice" role="status">{success}</div>}<div className="reporting-stats scoresheet-breakdown"><article><span>Total XP</span><strong>{detail.totalXp}</strong></article><article><span>Task Approval</span><strong>{detail.bySource.taskApprovalXp}</strong></article><article><span>Manual Award</span><strong>{detail.bySource.manualAwardXp}</strong></article><article><span>Raid</span><strong>{detail.bySource.raidXp}</strong></article></div>{items.length ? <LedgerRows items={items} onCorrect={(item) => { setSuccess(null); setCorrecting(item) }} /> : <State text="This participant has no XP ledger entries in the selected cycle." />}{error && items.length > 0 && <State text={error} error retry={() => void load(nextCursor)} />}{!error && nextCursor && <button className="button button--quiet load-more" type="button" disabled={loadingMore} onClick={() => void load(nextCursor)}>{loadingMore ? 'Loading more…' : 'Load more'}</button>}{correcting && <CorrectionPanel key={correcting.id} api={api} participantName={detail.participant.displayName} item={correcting} onClose={() => setCorrecting(null)} onCorrected={async () => { await refreshDetail(); await refreshSummary(); setCorrecting(null); setSuccess('XP correction recorded and authoritative Scoresheet data refreshed.') }} onConflict={async (entryId) => { const current = await refreshConflictTarget(entryId); if (current) setCorrecting(current); return current !== null }} />}</>}</section>
}

function correctionMessage(error: unknown) {
  if (!(error instanceof ScoresheetApiError)) return scoresheetErrorMessage(error)
  if (error.code === 'InvalidCorrectionAmount') return 'Enter a whole number of zero or more.'
  if (error.code === 'CorrectionReasonRequired') return 'Enter a reason for this correction.'
  if (error.code === 'CorrectionReasonTooLong') return 'Reason must be 2,000 characters or fewer.'
  if (error.code === 'CorrectionNoChange') return 'The requested amount already matches the current effective XP. Review the refreshed award before retrying.'
  if (error.code === 'CorrectionConflict') return 'The award changed while you were editing. Review the refreshed effective XP and explicitly retry.'
  if (error.code === 'XPEntryNotFound') return 'This award no longer exists. Close this form or reload the participant detail.'
  return scoresheetErrorMessage(error)
}

function CorrectionPanel({ api, participantName, item, onClose, onCorrected, onConflict }: { api: ScoresheetApi; participantName: string; item: ScoresheetLedgerItem; onClose: () => void; onCorrected: () => Promise<void>; onConflict: (entryId: string) => Promise<boolean> }) {
  const current = item.correction!.currentEffectiveAmount
  const [amount, setAmount] = useState(String(current)); const [reason, setReason] = useState(''); const [confirming, setConfirming] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [unavailable, setUnavailable] = useState(false)
  const value = Number(amount); const validAmount = amount.trim() !== '' && Number.isInteger(value) && value >= 0; const delta = validAmount ? value - current : null
  const review = () => { if (!validAmount) return setError('Enter a whole number of zero or more.'); if (!reason.trim()) return setError('Enter a reason for this correction.'); if (reason.trim().length > 2000) return setError('Reason must be 2,000 characters or fewer.'); setError(null); setConfirming(true) }
  const submit = async () => { if (pending || !validAmount) return; setPending(true); setError(null); try { await api.correctXp(item.id, { newAmount: value, reason: reason.trim() }); await onCorrected() } catch (requestError) { const conflict = requestError instanceof ScoresheetApiError && (requestError.code === 'CorrectionNoChange' || requestError.code === 'CorrectionConflict'); if (conflict) { try { if (!await onConflict(item.id)) setUnavailable(true) } catch { setUnavailable(true) } setConfirming(false) } setError(correctionMessage(requestError)) } finally { setPending(false) } }
  return <div className="correction-dialog" role="dialog" aria-modal="true" aria-labelledby="correction-heading"><header><div><p className="eyebrow">AUDITED ADJUSTMENT</p><h3 id="correction-heading">Correct XP</h3></div><button className="button button--quiet" type="button" onClick={onClose} disabled={pending}>Close</button></header>{unavailable ? <div className="inline-error" role="alert">This award is no longer available for correction. Close this form and reload the participant detail before taking another action.</div> : <><dl><div><dt>Participant</dt><dd>{participantName}</dd></div><div><dt>Source</dt><dd>{item.source.label}</dd></div><div><dt>Original award</dt><dd>{signed(item.amount)}</dd></div><div><dt>Current effective XP</dt><dd>{current} XP</dd></div></dl><p className="shared-note">This appends an audited XP adjustment. The original award is not edited or deleted.</p>{!confirming ? <><label className="field"><span>New effective XP</span><input aria-label="New effective XP" type="number" min="0" step="1" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><p className="correction-delta">Resulting change: <strong>{delta === null ? '—' : signed(delta)}</strong></p><label className="field"><span>Reason</span><textarea aria-label="Correction reason" maxLength={2000} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button className="button" type="button" onClick={review}>Review correction</button></div></> : <section className="correction-confirm"><h4>Confirm audited correction</h4><dl><div><dt>Original award</dt><dd>{signed(item.amount)}</dd></div><div><dt>Current effective XP</dt><dd>{current} XP</dd></div><div><dt>New effective XP</dt><dd>{value} XP</dd></div><div><dt>Resulting change</dt><dd>{signed(value - current)}</dd></div><div><dt>Reason</dt><dd>{reason.trim()}</dd></div></dl>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button className="button button--quiet" type="button" disabled={pending} onClick={() => setConfirming(false)}>Back</button><button className="button button--warning" type="button" disabled={pending} onClick={() => void submit()}>{pending ? 'Recording correction…' : 'Confirm correction'}</button></div></section>}</>}</div>
}
