import { useCallback, useEffect, useRef, useState } from 'react'
import { ScoresheetApiError, scoresheetErrorMessage, type ScoresheetApi } from './scoresheetApi'
import type { ManagerReportingCycle, ManagerReportingCycles, ManualAwardOptions, ScoresheetDetail, ScoresheetLedgerItem, ScoresheetSummary } from './types'

const signed = (amount: number) => amount >= 0 ? `+${amount} XP` : `−${Math.abs(amount)} XP`
const date = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
function State({ text, error, retry }: { text: string; error?: boolean; retry?: () => void }) { return <div className={`reporting-state${error ? ' reporting-state--error' : ''}`} role={error ? 'alert' : 'status'}><p>{text}</p>{retry && <button className="button button--quiet" type="button" onClick={retry}>Retry</button>}</div> }

export function ManagerScoresheet({ api, newRequestId = () => crypto.randomUUID() }: { api: ScoresheetApi; newRequestId?: () => string }) {
  const [cycles, setCycles] = useState<ManagerReportingCycles | null>(null)
  const [cycleId, setCycleId] = useState('')
  const [summary, setSummary] = useState<ScoresheetSummary | null>(null)
  const [loadingCycles, setLoadingCycles] = useState(true)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [awardOpen, setAwardOpen] = useState(false)
  const [awardRequestId, setAwardRequestId] = useState('')
  const [awardSuccess, setAwardSuccess] = useState<string | null>(null)
  const summaryRequest = useRef(0)
  const refreshOpenDetail = useRef<(() => Promise<void>) | null>(null)
  const activeCycle = useRef(cycleId)
  activeCycle.current = cycleId
  const loadCycles = useCallback(async () => { setLoadingCycles(true); setError(null); try { const result = await api.getReportingCycles(); setCycles(result); setCycleId((current) => result.cycles.some((cycle) => cycle.id === current) ? current : result.defaultCycleId ?? '') } catch (requestError) { setError(scoresheetErrorMessage(requestError)) } finally { setLoadingCycles(false) } }, [api])
  const loadSummary = useCallback(async () => { if (!cycleId) return; const request = ++summaryRequest.current; setLoading(true); setError(null); setSelectedId(null); try { const result = await api.getScoresheet(cycleId); if (request === summaryRequest.current) setSummary(result) } catch (requestError) { if (request === summaryRequest.current) setError(scoresheetErrorMessage(requestError)) } finally { if (request === summaryRequest.current) setLoading(false) } }, [api, cycleId])
  const refreshSummary = useCallback(async () => { if (activeCycle.current !== cycleId) throw new Error('Reporting cycle changed.'); const request = ++summaryRequest.current; const result = await api.getScoresheet(cycleId); if (request !== summaryRequest.current || activeCycle.current !== cycleId) throw new Error('Reporting cycle changed.'); setSummary(result) }, [api, cycleId])
  useEffect(() => { void loadCycles() }, [loadCycles])
  useEffect(() => { void loadSummary() }, [loadSummary])
  if (loadingCycles) return <State text="Loading manager reporting cycles…" />
  if (error && !cycles) return <State text={error} error retry={() => void loadCycles()} />
  if (!cycles?.cycles.length || !cycleId) return <State text="No reporting cycles are available for the Scoresheet." />
  const selectedCycle = cycles.cycles.find((cycle) => cycle.id === cycleId)!
  return <div className="reporting-area"><div className="cycle-context"><div><p className="eyebrow">MANAGER REPORTING</p><strong>{selectedCycle.name}</strong><span>Cycle selection changes this Scoresheet reporting context.</span></div><label><span>Reporting cycle</span><select aria-label="Scoresheet reporting cycle" value={cycleId} onChange={(event) => { setAwardOpen(false); setAwardSuccess(null); setAwardRequestId(newRequestId()); setSelectedId(null); setCycleId(event.target.value) }}>{cycles.cycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{cycle.name} · {cycle.status}</option>)}</select></label></div>
    <header className="section-heading scoresheet-heading"><div><p className="eyebrow">APPEND-ONLY XP LEDGER</p><h2>Scoresheet summary</h2><p>All cycle participants are shown, including zero-XP and inactive roster entries.</p></div><button className="button" type="button" onClick={() => { setAwardSuccess(null); if (!awardRequestId) setAwardRequestId(newRequestId()); setAwardOpen(true) }}>Award XP</button></header>
    {awardSuccess && <div className="success-notice" role="status">{awardSuccess}</div>}
    {awardOpen && <ManualAwardPanel api={api} cycle={selectedCycle} requestId={awardRequestId} onClose={() => setAwardOpen(false)} onReset={() => { setAwardSuccess(null); setAwardRequestId(newRequestId()) }} onCreated={async (participantId, participantName) => { if (selectedId === participantId && refreshOpenDetail.current) await refreshOpenDetail.current(); await refreshSummary(); setAwardSuccess(`Manual XP award for ${participantName} recorded and authoritative Scoresheet data refreshed.`); setAwardRequestId(newRequestId()) }} />}
    {loading ? <State text="Loading Scoresheet…" /> : error ? <State text={error} error retry={() => void loadSummary()} /> : !summary?.rows.length ? <State text="No participants are enrolled in this reporting cycle." /> : <div className="table-wrap"><table className="scoresheet-table"><thead><tr><th>Participant</th><th>Status</th><th>Task Approval XP</th><th>Manual Award XP</th><th>Raid XP</th><th>Adjustments</th><th>Total XP</th></tr></thead><tbody>{summary.rows.map((row) => <tr key={row.participantId}><td><button className="participant-link" type="button" onClick={() => setSelectedId(row.participantId)}>{row.displayName}</button></td><td><span className="participant-status">{row.participantStatus}</span></td><td>{row.bySource.taskApprovalXp}</td><td>{row.bySource.manualAwardXp}</td><td>{row.bySource.raidXp}</td><td className={row.byEntryType.netAdjustmentXp < 0 ? 'xp-negative' : ''}>{row.byEntryType.netAdjustmentXp}</td><td><strong>{row.totalXp}</strong></td></tr>)}</tbody></table></div>}
    {selectedId && <ParticipantDetail key={`${cycleId}:${selectedId}`} api={api} cycleId={cycleId} participantId={selectedId} onClose={() => setSelectedId(null)} refreshSummary={refreshSummary} registerRefresh={(refresh) => { refreshOpenDetail.current = refresh }} />}
  </div>
}

function manualAwardMessage(error: unknown) {
  if (!(error instanceof ScoresheetApiError)) return scoresheetErrorMessage(error)
  const messages: Record<string, string> = {
    InvalidManualAwardRequestId: 'This award attempt has an invalid request identifier. Deliberately reset the form before trying again.',
    InvalidManualAwardCycleId: 'The selected reporting cycle is invalid.', InvalidManualAwardParticipantId: 'Select an eligible participant.', InvalidAwardCategoryId: 'Select an available award category.',
    InvalidManualAwardAmount: 'Enter a positive whole-number XP amount.', ManualAwardReasonRequired: 'Enter a reason for this award.', ManualAwardReasonTooLong: 'Reason must be 2,000 characters or fewer.',
    ManualAwardCycleNotFound: 'The selected reporting cycle no longer exists.', ManualAwardParticipantNotFound: 'The participant is no longer enrolled in this cycle.', AwardCategoryNotFound: 'The award category is no longer available.',
    ManualAwardCycleUnavailable: 'This reporting cycle is no longer available for manual awards. Review the cycle before continuing.', ManualAwardParticipantIneligible: 'This participant is no longer eligible for a manual award. Review the refreshed options.',
    ManualAwardRequestConflict: 'This request identifier conflicts with another award attempt. Review the values, then deliberately reset to start a new award.', ManualAwardDependencyUnavailable: 'Manual Award is temporarily unavailable. Your request identifier and entered values have been preserved for explicit retry.',
  }
  return error.code && messages[error.code] ? messages[error.code] : scoresheetErrorMessage(error)
}

function ManualAwardPanel({ api, cycle, requestId, onClose, onReset, onCreated }: { api: ScoresheetApi; cycle: ManagerReportingCycle; requestId: string; onClose: () => void; onReset: () => void; onCreated: (participantId: string, participantName: string) => Promise<void> }) {
  const [options, setOptions] = useState<ManualAwardOptions | null>(null); const [optionsLoading, setOptionsLoading] = useState(true); const [optionsError, setOptionsError] = useState<string | null>(null); const [participantId, setParticipantId] = useState(''); const [categoryId, setCategoryId] = useState(''); const [amount, setAmount] = useState(''); const [reason, setReason] = useState(''); const [confirming, setConfirming] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null)
  const loadOptions = useCallback(async () => { setOptionsLoading(true); setOptionsError(null); try { const result = await api.getManualAwardOptions(cycle.id); setOptions(result); setParticipantId((current) => result.participants.some((option) => option.participantId === current) ? current : ''); setCategoryId((current) => result.categories.some((option) => option.awardCategoryId === current) ? current : '') } catch (requestError) { setOptionsError(manualAwardMessage(requestError)) } finally { setOptionsLoading(false) } }, [api, cycle.id])
  useEffect(() => { void loadOptions() }, [loadOptions])
  useEffect(() => { setParticipantId(''); setCategoryId(''); setAmount(''); setReason(''); setConfirming(false); setError(null) }, [requestId])
  const numericAmount = Number(amount); const validAmount = amount.trim() !== '' && Number.isInteger(numericAmount) && numericAmount > 0; const participant = options?.participants.find((option) => option.participantId === participantId); const category = options?.categories.find((option) => option.awardCategoryId === categoryId)
  const review = () => { if (!participant) return setError('Select an eligible participant.'); if (!category) return setError('Select an available award category.'); if (!validAmount) return setError('Enter a positive whole-number XP amount.'); if (!reason.trim()) return setError('Enter a reason for this award.'); if (reason.trim().length > 2000) return setError('Reason must be 2,000 characters or fewer.'); setError(null); setConfirming(true) }
  const submit = async () => { if (pending || !participant || !category || !validAmount) return; setPending(true); setError(null); try { await api.createManualAward({ requestId, cycleId: cycle.id, participantId, awardCategoryId: categoryId, amount: numericAmount, reason: reason.trim() }); await onCreated(participantId, participant.displayName) } catch (requestError) { setError(manualAwardMessage(requestError)); const refreshCodes = ['ManualAwardCycleUnavailable', 'ManualAwardParticipantIneligible', 'AwardCategoryNotFound', 'ManualAwardParticipantNotFound']; if (requestError instanceof ScoresheetApiError && requestError.code && refreshCodes.includes(requestError.code)) void loadOptions(); setConfirming(false) } finally { setPending(false) } }
  return <section className="manual-award-panel" role="dialog" aria-modal="true" aria-labelledby="manual-award-heading"><header><div><p className="eyebrow">AUDITED MANUAL AWARD</p><h3 id="manual-award-heading">Award XP</h3></div><button className="button button--quiet" type="button" disabled={pending} onClick={onClose}>Close</button></header><div className="manual-award-cycle"><span>Cycle</span><strong>{cycle.name} · {cycle.code}</strong></div><p className="shared-note">This creates a new audited, append-only XP award. It does not edit an existing ledger entry.</p>{optionsLoading ? <State text="Loading Manual Award options…" /> : optionsError ? <State text={optionsError} error retry={() => void loadOptions()} /> : !options ? null : !confirming ? <><label className="field"><span>Participant</span><select aria-label="Award participant" value={participantId} onChange={(event) => setParticipantId(event.target.value)}><option value="">Select participant…</option>{options.participants.map((option) => <option key={option.participantId} value={option.participantId}>{option.displayName}</option>)}</select></label><label className="field"><span>Award Category</span><select aria-label="Award category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Select category…</option>{options.categories.map((option) => <option key={option.awardCategoryId} value={option.awardCategoryId}>{option.name} · {option.code}</option>)}</select></label><label className="field"><span>XP Amount</span><input aria-label="Award XP amount" type="number" min="1" step="1" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="field"><span>Reason</span><textarea aria-label="Manual Award reason" maxLength={2000} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button className="button button--quiet" type="button" disabled={pending} onClick={onReset}>Reset / new award</button><button className="button" type="button" onClick={review}>Review award</button></div></> : <section className="manual-award-confirm"><h4>Confirm Manual Award</h4><dl><div><dt>Participant</dt><dd>{participant!.displayName}</dd></div><div><dt>Cycle</dt><dd>{cycle.name} · {cycle.code}</dd></div><div><dt>Award Category</dt><dd>{category!.name}</dd></div><div><dt>XP Amount</dt><dd>+{numericAmount} XP</dd></div><div><dt>Reason</dt><dd>{reason.trim()}</dd></div></dl><p>This will append a new audited XP ledger entry.</p>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button className="button button--quiet" type="button" disabled={pending} onClick={() => setConfirming(false)}>Back</button><button className="button button--warning" type="button" disabled={pending} onClick={() => void submit()}>{pending ? 'Awarding XP…' : 'Confirm award'}</button></div></section>}</section>
}

function LedgerRows({ items, onCorrect }: { items: ScoresheetLedgerItem[]; onCorrect: (item: ScoresheetLedgerItem) => void }) { return <div className="activity-rows scoresheet-ledger">{items.map((item) => <article key={item.id}><strong className={item.amount < 0 ? 'xp-negative' : 'xp-positive'}>{signed(item.amount)}</strong><div><h3>{item.source.label}</h3><p>{item.entryType} · {item.sourceType}</p><p>{item.reason}</p><span>{date(item.awardedAt)}{item.reversesEntryId ? ` · Reverses ${item.reversesEntryId}` : ''}</span>{item.correction !== null && <button className="button button--quiet correction-trigger" type="button" onClick={() => onCorrect(item)}>Correct XP</button>}</div></article>)}</div> }

function ParticipantDetail({ api, cycleId, participantId, onClose, refreshSummary, registerRefresh }: { api: ScoresheetApi; cycleId: string; participantId: string; onClose: () => void; refreshSummary: () => Promise<void>; registerRefresh: (refresh: (() => Promise<void>) | null) => void }) {
  const [detail, setDetail] = useState<ScoresheetDetail | null>(null); const [items, setItems] = useState<ScoresheetLedgerItem[]>([]); const [nextCursor, setNextCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState<string | null>(null); const [correcting, setCorrecting] = useState<ScoresheetLedgerItem | null>(null); const [success, setSuccess] = useState<string | null>(null)
  const load = useCallback(async (cursor?: string | null) => { cursor ? setLoadingMore(true) : setLoading(true); setError(null); try { const result = await api.getParticipant(participantId, cycleId, cursor); setDetail(result); setItems((current) => cursor ? [...current, ...result.items.filter((item) => !current.some((existing) => existing.id === item.id))] : result.items); setNextCursor(result.nextCursor) } catch (requestError) { setError(scoresheetErrorMessage(requestError)) } finally { setLoading(false); setLoadingMore(false) } }, [api, cycleId, participantId])
  const refreshDetail = useCallback(async () => { const result = await api.getParticipant(participantId, cycleId, null); setDetail(result); setItems(result.items); setNextCursor(result.nextCursor); return result }, [api, cycleId, participantId])
  const refreshConflictTarget = useCallback(async (entryId: string) => {
    const first = await api.getParticipant(participantId, cycleId, null); const refreshed = [...first.items]; let target = refreshed.find((item) => item.id === entryId); let cursor = first.nextCursor; const followed = new Set<string>()
    while (!target && cursor && !followed.has(cursor)) { followed.add(cursor); const page = await api.getParticipant(participantId, cycleId, cursor); for (const item of page.items) if (!refreshed.some((existing) => existing.id === item.id)) refreshed.push(item); target = refreshed.find((item) => item.id === entryId); cursor = page.nextCursor }
    setDetail(first); setItems(refreshed); setNextCursor(cursor)
    return target?.correction ? target : null
  }, [api, cycleId, participantId])
  useEffect(() => { void load(null) }, [load])
  useEffect(() => { registerRefresh(async () => { await refreshDetail() }); return () => registerRefresh(null) }, [refreshDetail, registerRefresh])
  return <section className="scoresheet-detail reporting-card" aria-label="Participant Scoresheet detail">{loading ? <State text="Loading participant ledger…" /> : error && !detail ? <State text={error} error retry={() => void load(null)} /> : detail && <><header className="detail-heading"><div><p className="eyebrow">PARTICIPANT DRILL-DOWN</p><h2>{detail.participant.displayName}</h2><span className="participant-status">{detail.participant.participantStatus}</span></div><button className="button button--quiet" type="button" onClick={onClose}>Close</button></header>{success && <div className="success-notice" role="status">{success}</div>}<div className="reporting-stats scoresheet-breakdown"><article><span>Total XP</span><strong>{detail.totalXp}</strong></article><article><span>Task Approval</span><strong>{detail.bySource.taskApprovalXp}</strong></article><article><span>Manual Award</span><strong>{detail.bySource.manualAwardXp}</strong></article><article><span>Raid</span><strong>{detail.bySource.raidXp}</strong></article></div>{items.length ? <LedgerRows items={items} onCorrect={(item) => { setSuccess(null); setCorrecting(item) }} /> : <State text="This participant has no XP ledger entries in the selected cycle." />}{error && items.length > 0 && <State text={error} error retry={() => void load(nextCursor)} />}{!error && nextCursor && <button className="button button--quiet load-more" type="button" disabled={loadingMore} onClick={() => void load(nextCursor)}>{loadingMore ? 'Loading more…' : 'Load more'}</button>}{correcting && <CorrectionPanel key={correcting.id} api={api} participantName={detail.participant.displayName} item={correcting} onClose={() => setCorrecting(null)} onCorrected={async () => { await refreshDetail(); await refreshSummary(); setCorrecting(null); setSuccess('XP correction recorded and authoritative Scoresheet data refreshed.') }} onConflict={async (entryId) => { const current = await refreshConflictTarget(entryId); if (current) setCorrecting(current); return current !== null }} />}</>}</section>
}

function correctionMessage(error: unknown) {
  if (!(error instanceof ScoresheetApiError)) return scoresheetErrorMessage(error)
  if (error.code === 'InvalidCorrectionAmount') return 'Enter a whole number of zero or more.'
  if (error.code === 'CorrectionReasonRequired') return 'Enter a reason for this correction.'
  if (error.code === 'CorrectionReasonTooLong') return 'Reason must be 2,000 characters or fewer.'
  if (error.code === 'CorrectionNoChange') return 'The requested amount already matches the current effective XP. Review the refreshed award before retrying.'
  if (error.code === 'CorrectionConflict') return 'The award changed while you were editing. Review the refreshed effective XP and explicitly retry.'
  if (error.code === 'XPEntryNotFound') return 'This award no longer exists. Close this form or reload the participant detail.'
  return scoresheetErrorMessage(error)
}

function CorrectionPanel({ api, participantName, item, onClose, onCorrected, onConflict }: { api: ScoresheetApi; participantName: string; item: ScoresheetLedgerItem; onClose: () => void; onCorrected: () => Promise<void>; onConflict: (entryId: string) => Promise<boolean> }) {
  const current = item.correction!.currentEffectiveAmount
  const [amount, setAmount] = useState(String(current)); const [reason, setReason] = useState(''); const [confirming, setConfirming] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [unavailable, setUnavailable] = useState(false)
  const value = Number(amount); const validAmount = amount.trim() !== '' && Number.isInteger(value) && value >= 0; const delta = validAmount ? value - current : null
  const review = () => { if (!validAmount) return setError('Enter a whole number of zero or more.'); if (!reason.trim()) return setError('Enter a reason for this correction.'); if (reason.trim().length > 2000) return setError('Reason must be 2,000 characters or fewer.'); setError(null); setConfirming(true) }
  const submit = async () => { if (pending || !validAmount) return; setPending(true); setError(null); try { await api.correctXp(item.id, { newAmount: value, reason: reason.trim() }); await onCorrected() } catch (requestError) { const conflict = requestError instanceof ScoresheetApiError && (requestError.code === 'CorrectionNoChange' || requestError.code === 'CorrectionConflict'); if (conflict) { try { if (!await onConflict(item.id)) setUnavailable(true) } catch { setUnavailable(true) } setConfirming(false) } setError(correctionMessage(requestError)) } finally { setPending(false) } }
  return <div className="correction-dialog" role="dialog" aria-modal="true" aria-labelledby="correction-heading"><header><div><p className="eyebrow">AUDITED ADJUSTMENT</p><h3 id="correction-heading">Correct XP</h3></div><button className="button button--quiet" type="button" onClick={onClose} disabled={pending}>Close</button></header>{unavailable ? <div className="inline-error" role="alert">This award is no longer available for correction. Close this form and reload the participant detail before taking another action.</div> : <><dl><div><dt>Participant</dt><dd>{participantName}</dd></div><div><dt>Source</dt><dd>{item.source.label}</dd></div><div><dt>Original award</dt><dd>{signed(item.amount)}</dd></div><div><dt>Current effective XP</dt><dd>{current} XP</dd></div></dl><p className="shared-note">This appends an audited XP adjustment. The original award is not edited or deleted.</p>{!confirming ? <><label className="field"><span>New effective XP</span><input aria-label="New effective XP" type="number" min="0" step="1" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><p className="correction-delta">Resulting change: <strong>{delta === null ? '—' : signed(delta)}</strong></p><label className="field"><span>Reason</span><textarea aria-label="Correction reason" maxLength={2000} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button className="button" type="button" onClick={review}>Review correction</button></div></> : <section className="correction-confirm"><h4>Confirm audited correction</h4><dl><div><dt>Original award</dt><dd>{signed(item.amount)}</dd></div><div><dt>Current effective XP</dt><dd>{current} XP</dd></div><div><dt>New effective XP</dt><dd>{value} XP</dd></div><div><dt>Resulting change</dt><dd>{signed(value - current)}</dd></div><div><dt>Reason</dt><dd>{reason.trim()}</dd></div></dl>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button className="button button--quiet" type="button" disabled={pending} onClick={() => setConfirming(false)}>Back</button><button className="button button--warning" type="button" disabled={pending} onClick={() => void submit()}>{pending ? 'Recording correction…' : 'Confirm correction'}</button></div></section>}</>}</div>
}
