import { expect, test } from '@playwright/test'
import { captureEvidence } from './evidence'

test('manager Scoresheet reconciles workflow XP and exposes append-only participant detail', async ({ page }) => {
  await page.goto('/')
  const identity = page.getByRole('combobox', { name: 'Demo identity' })
  await identity.selectOption('participant')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Participant' })).toBeVisible()
  const me = await page.request.get('/api/auth/me')
  expect(me.status()).toBe(200)
  const participantId = (await me.json()).participantId as string
  expect(participantId).toMatch(/^[0-9a-f-]{36}$/i)

  await page.getByRole('button', { name: 'Challenges' }).click()
  const task = page.locator('.task-row').filter({ hasText: 'Complete the synthetic shared task' })
  await task.getByRole('button', { name: 'Submit work' }).click()
  await page.getByRole('textbox', { name: 'Evidence *' }).fill('Synthetic Scoresheet acceptance evidence')
  await page.getByRole('button', { name: 'Submit for review' }).click()
  await expect(page.getByText('Submitted', { exact: true }).first()).toBeVisible()

  await identity.selectOption('manager')
  await page.getByRole('button', { name: 'Review queue' }).click()
  await expect(page.getByText('Synthetic Scoresheet acceptance evidence')).toBeVisible()
  page.once('dialog', dialog => void dialog.accept())
  await page.getByRole('button', { name: 'Approve all 2' }).click()
  await expect(page.getByText('All caught up—nothing is waiting for review.')).toBeVisible()

  const cyclesResponse = await page.request.get('/api/manager/reporting-cycles')
  expect(cyclesResponse.status()).toBe(200)
  const cycles = await cyclesResponse.json() as { defaultCycleId: string }
  const detailResponse = await page.request.get(`/api/manager/scoresheet/${participantId}?cycleId=${cycles.defaultCycleId}&limit=25`)
  expect(detailResponse.status()).toBe(200)
  const detail = await detailResponse.json() as { items: Array<{ id: string; entryType: string; sourceType: string }> }
  const taskGrant = detail.items.find(item => item.entryType === 'Grant' && item.sourceType === 'TaskApproval')
  expect(taskGrant).toBeTruthy()
  const correction = await page.request.post(`/api/manager/xp/${taskGrant!.id}/corrections`, { data: { newAmount: 20, reason: 'Synthetic Scoresheet acceptance adjustment' } })
  expect(correction.status()).toBe(200)

  const summaryResponse = await page.request.get(`/api/manager/scoresheet?cycleId=${cycles.defaultCycleId}`)
  expect(summaryResponse.status()).toBe(200)
  const summary = await summaryResponse.json() as { rows: Array<{ participantId: string; displayName: string; participantStatus: string; totalXp: number; bySource: { taskApprovalXp: number; manualAwardXp: number; raidXp: number }; byEntryType: { netAdjustmentXp: number } }> }

  await page.getByRole('button', { name: 'Scoresheet' }).click()
  const cycleSelector = page.getByLabel('Scoresheet reporting cycle')
  await expect(cycleSelector).toHaveValue(cycles.defaultCycleId)
  await expect(page.getByText('Cycle selection changes this Scoresheet reporting context.')).toBeVisible()
  const table = page.getByRole('table')
  await expect(table).toBeVisible()
  const participantRow = table.getByRole('row').filter({ hasText: 'Synthetic Participant' })
  const teammateRow = table.getByRole('row').filter({ hasText: 'Synthetic Teammate' })
  const managerRow = table.getByRole('row').filter({ hasText: 'Synthetic Manager' })
  for (const expected of summary.rows) {
    const row = table.getByRole('row').filter({ hasText: expected.displayName })
    const cells = row.getByRole('cell')
    await expect(row).toBeVisible()
    await expect(cells.nth(1)).toHaveText(expected.participantStatus)
    await expect(cells.nth(2)).toHaveText(String(expected.bySource.taskApprovalXp))
    await expect(cells.nth(3)).toHaveText(String(expected.bySource.manualAwardXp))
    await expect(cells.nth(4)).toHaveText(String(expected.bySource.raidXp))
    await expect(cells.nth(5)).toHaveText(String(expected.byEntryType.netAdjustmentXp))
    await expect(cells.nth(6)).toHaveText(String(expected.totalXp))
  }
  expect(summary.rows.every(row => ['Active', 'Withdrawn', 'Inactive'].includes(row.participantStatus))).toBe(true)
  expect(summary.rows.some(row => row.totalXp === 0)).toBe(true)
  await expect(participantRow).toBeVisible()
  await expect(teammateRow).toBeVisible()
  await expect(managerRow).toBeVisible()
  await captureEvidence(page, 'docker-manager-scoresheet', '01-scoresheet-summary.png')
  await captureEvidence(page, 'docker-manager-scoresheet', '02-zero-xp-active-status.png')

  await participantRow.getByRole('button', { name: 'Synthetic Participant' }).click()
  const ledger = page.getByLabel('Participant Scoresheet detail')
  await expect(ledger).toBeVisible()
  await expect(ledger.getByText('+25 XP').first()).toBeVisible()
  await expect(ledger.getByText('−5 XP').first()).toBeVisible()
  await expect(ledger.getByText('+10 XP').first()).toBeVisible()
  await expect(ledger.getByText('Synthetic Shared Challenge · Complete the synthetic shared task').first()).toBeVisible()
  await expect(ledger.getByText('Synthetic Welcome Award')).toBeVisible()
  await expect(ledger.getByText('Synthetic Scoresheet acceptance adjustment').first()).toBeVisible()
  await expect(ledger.getByText(/Reversal · TaskApproval/).first()).toBeVisible()
  await expect(ledger.getByText(/Grant · ManualAward/).first()).toBeVisible()
  await expect(ledger.getByRole('button', { name: 'Load more' })).toHaveCount(0)
  await captureEvidence(page, 'docker-manager-scoresheet', '03-participant-ledger-drill-down.png')
  await captureEvidence(page, 'docker-manager-scoresheet', '04-signed-adjustment-source.png')

  await identity.selectOption('participant')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Participant' })).toBeVisible()
  await page.getByRole('button', { name: 'Leaderboard' }).click()
  await expect(page.getByRole('heading', { name: 'Leaderboard', level: 2 })).toBeVisible()
  await identity.selectOption('manager')
  await page.getByRole('button', { name: 'Review queue' }).click()
  await expect(page.getByText('All caught up—nothing is waiting for review.')).toBeVisible()
  await page.getByRole('button', { name: 'Challenges' }).click()
  await expect(page.getByRole('heading', { name: 'Challenge administration', level: 2 })).toBeVisible()
})
