import { expect, test } from '@playwright/test'
import path from 'node:path'
import { captureEvidence } from './evidence'

const proof = path.resolve(__dirname, 'fixtures', 'synthetic-proof-one.txt')

test('clean Docker participant reporting remains integrated with submission approval', async ({ page }) => {
  await page.goto('/')
  const identity = page.getByRole('combobox', { name: 'Demo identity' })
  await identity.selectOption('participant')

  await expect(page.getByLabel('Reporting cycle')).toHaveValue('60000000-0000-4000-8000-000000000001')
  await expect(page.getByText('REPORTING CONTEXT')).toBeVisible()
  await expect(page.getByText('This selection changes reporting views only. Challenge eligibility still follows each challenge’s dates and status.')).toBeVisible()
  await expect(page.getByText('Total XP', { exact: true }).locator('..')).toContainText('10')
  await expect(page.getByText('Individual rank').locator('..')).toContainText('#1')
  await expect(page.getByText('Eligible challenges').locator('..')).toContainText('1')
  await expect(page.getByText('No submissions in this reporting cycle.')).toBeVisible()
  await expect(page.getByText('Synthetic Welcome Award')).toBeVisible()
  await expect(page.getByText('+10 XP')).toBeVisible()
  const raidPasses = page.getByRole('heading', { name: 'Raid passes' }).locator('xpath=ancestor::section[1]')
  await expect(raidPasses).toContainText('NON-XP RESOURCE')
  await expect(raidPasses).toContainText('Not included in Total XP')
  await expect(raidPasses).toContainText('2 assigned · 1 used')
  await captureEvidence(page, 'docker-reporting', '01-participant-dashboard.png')

  await page.getByRole('button', { name: 'My team' }).click()
  await expect(page.getByText('MY CYCLE TEAM')).toBeVisible()
  const cycleTeam = page.getByRole('heading', { name: 'Synthetic Quest Crew' }).locator('xpath=ancestor::section[1]')
  await expect(cycleTeam).toBeVisible()
  await expect(page.getByText('CHALLENGE GROUPS')).toBeVisible()
  const challengeGroups = page.getByRole('heading', { name: 'Challenge participation snapshots' }).locator('xpath=ancestor::section[1]')
  await expect(challengeGroups).toBeVisible()
  await expect(cycleTeam.getByText('Synthetic Participant', { exact: true })).toBeVisible()
  await expect(cycleTeam.getByText('Synthetic Teammate', { exact: true })).toBeVisible()
  await expect(cycleTeam.getByText('You', { exact: true })).toBeVisible()
  await expect(challengeGroups.getByText('Synthetic Participant', { exact: true })).toBeVisible()
  await expect(challengeGroups.getByText('Synthetic Teammate', { exact: true })).toBeVisible()
  await expect(challengeGroups.getByText('You', { exact: true })).toBeVisible()
  await expect(page.getByText(/team XP|team rank|team leaderboard/i)).toHaveCount(0)
  await captureEvidence(page, 'docker-reporting', '02-cycle-team-and-challenge-groups.png')

  await page.getByRole('button', { name: 'Leaderboard' }).click()
  const rows = page.getByRole('row')
  await expect(rows.filter({ hasText: 'Synthetic Participant' })).toContainText('1')
  await expect(rows.filter({ hasText: 'Synthetic Participant' })).toContainText('10 XP')
  await expect(rows.filter({ hasText: 'Synthetic Participant' })).toContainText('You')
  await expect(rows.filter({ hasText: 'Synthetic Manager' })).toContainText('2')
  await expect(rows.filter({ hasText: 'Synthetic Manager' })).toContainText('0 XP')
  await expect(rows.filter({ hasText: 'Synthetic Teammate' })).toContainText('2')
  await expect(rows.filter({ hasText: 'Synthetic Teammate' })).toContainText('0 XP')
  await captureEvidence(page, 'docker-reporting', '03-individual-leaderboard.png')

  await page.getByRole('button', { name: 'XP Activity' }).click()
  await expect(page.getByText('+10 XP')).toBeVisible()
  await expect(page.getByText('Synthetic Welcome Award')).toBeVisible()
  await expect(page.getByText('Synthetic local-development showcase award')).toBeVisible()
  await expect(page.getByText(/Grant ·/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Load more' })).toHaveCount(0)
  await captureEvidence(page, 'docker-reporting', '04-xp-activity-manual-award.png')

  await page.getByRole('button', { name: 'Challenges' }).click()
  const attachmentTask = page.locator('.task-row').filter({ hasText: 'Upload synthetic attachment evidence' })
  await attachmentTask.getByRole('button', { name: 'Submit work' }).click()
  await page.locator('input[type=file]').setInputFiles(proof)
  await page.getByRole('button', { name: 'Submit for review' }).click()
  await expect(page.getByText('Submitted', { exact: true }).first()).toBeVisible()

  await identity.selectOption('manager')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Manager' })).toBeVisible()
  await page.getByRole('button', { name: 'Review queue' }).click()
  const attachment = page.getByRole('link', { name: 'synthetic-proof-one.txt' })
  await expect(attachment).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await attachment.click()
  expect((await downloadPromise).suggestedFilename()).toBe('synthetic-proof-one.txt')
  page.once('dialog', dialog => void dialog.accept())
  await page.getByRole('button', { name: 'Approve all 2' }).click()
  await expect(page.getByText('All caught up—nothing is waiting for review.')).toBeVisible()
  await captureEvidence(page, 'docker-reporting', '05-manager-attachment-approved.png')

  await identity.selectOption('participant')
  await page.getByRole('button', { name: 'My activity' }).click()
  await expect(page.getByText('Approved', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Awarded task result: 25 XP')).toBeVisible()
  await page.getByRole('button', { name: 'XP Activity' }).click()
  await expect(page.getByText('+25 XP')).toBeVisible()
  await expect(page.getByText('Synthetic Shared Challenge · Upload synthetic attachment evidence')).toBeVisible()
  await expect(page.getByText('Task submission approved')).toBeVisible()
  await captureEvidence(page, 'docker-reporting', '06-xp-activity-task-approval.png')
})
