import { expect, request as playwrightRequest, test } from '@playwright/test'
import path from 'node:path'
import { captureEvidence } from './evidence'

const firstProof = path.resolve(__dirname, 'fixtures', 'synthetic-proof-one.txt')
const secondProof = path.resolve(__dirname, 'fixtures', 'synthetic-proof-two.txt')

test('clean Docker Compose supports the complete private attachment showcase', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('DEVELOPMENT ONLY')).toBeVisible()
  await captureEvidence(page, 'docker-step7', '01-demo-auth.png')

  const identity = page.getByRole('combobox', { name: 'Demo identity' })
  await identity.selectOption('participant')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Participant' })).toBeVisible()
  expect(await (await page.request.get('/api/submissions/mine')).json()).toEqual([])

  await page.getByRole('button', { name: 'Challenges' }).click()
  const attachmentTask = page.locator('.task-row').filter({ hasText: 'Upload synthetic attachment evidence' })
  await expect(attachmentTask).toContainText('25 XP')
  await captureEvidence(page, 'docker-step7', '02-attachment-task.png')
  await attachmentTask.getByRole('button', { name: 'Submit work' }).click()
  await page.locator('input[type=file]').setInputFiles(firstProof)
  await expect(page.getByText('synthetic-proof-one.txt')).toBeVisible()
  await expect(page.getByText('1 KiB')).toBeVisible()
  await captureEvidence(page, 'docker-step7', '03-file-selected.png')
  await page.getByRole('button', { name: 'Submit for review' }).click()
  await expect(page.getByText('Submitted', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'synthetic-proof-one.txt' })).toBeVisible()
  await captureEvidence(page, 'docker-step7', '04-submitted.png')

  const claimantContentUrl = await page.getByRole('link', { name: 'synthetic-proof-one.txt' }).getAttribute('href')
  expect(claimantContentUrl).toMatch(/^\/api\/submission-evidence\/[0-9a-f-]+\/content$/)
  const claimantContent = await page.request.get(claimantContentUrl!)
  expect(claimantContent.status()).toBe(200)
  const disposition = claimantContent.headers()['content-disposition']
  expect(disposition).not.toMatch(/[\r\n]/)
  expect(disposition.split(';', 1)[0].trim().toLowerCase()).toBe('attachment')
  const extendedFilename = disposition.match(/(?:^|;)\s*filename\*\s*=\s*([^']*)''([^;]*)/i)
  expect(extendedFilename, 'Content-Disposition must contain an RFC 5987 filename* parameter').not.toBeNull()
  expect(extendedFilename![1].toLowerCase()).toBe('utf-8')
  expect(decodeURIComponent(extendedFilename![2].trim())).toBe('synthetic-proof-one.txt')
  expect(claimantContent.headers()['x-content-type-options']).toBe('nosniff')
  expect(claimantContent.headers()['cache-control']).toContain('private')
  expect(claimantContent.headers()['cache-control']).toContain('no-store')

  const anonymous = await playwrightRequest.newContext({ baseURL: 'http://localhost:5173' })
  expect((await anonymous.get(claimantContentUrl!)).status()).toBe(401)
  await anonymous.dispose()
  expect((await page.request.get('/api/submission-evidence/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/content')).status()).toBe(404)

  await identity.selectOption('manager')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Manager' })).toBeVisible()
  await page.getByRole('button', { name: 'Review queue' }).click()
  const managerAttachment = page.getByRole('link', { name: 'synthetic-proof-one.txt' })
  await expect(managerAttachment).toBeVisible()
  await captureEvidence(page, 'docker-step7', '05-manager-attachment-review.png')
  const downloadPromise = page.waitForEvent('download')
  await managerAttachment.click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('synthetic-proof-one.txt')
  await captureEvidence(page, 'docker-step7', '06-attachment-opened.png')
  await page.getByLabel('Manager comment').fill('Please append a second synthetic proof file.')
  await page.getByRole('button', { name: 'Needs evidence' }).click()

  await identity.selectOption('participant')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Participant' })).toBeVisible()
  await page.getByRole('button', { name: 'My activity' }).click()
  const history = page.getByLabel('Submission history')
  await expect(history).toContainText('Needs evidence')
  await expect(history).toContainText('Please append a second synthetic proof file.')
  await expect(page.getByRole('link', { name: 'synthetic-proof-one.txt' })).toBeVisible()
  await expect(page.getByText('Existing accepted attachments are retained')).toBeVisible()
  await captureEvidence(page, 'docker-step7', '07-needs-evidence.png')
  await captureEvidence(page, 'docker-step7', '08-participant-retained-attachment.png')
  await page.locator('.resubmit input[type=file]').setInputFiles(secondProof)
  await page.getByLabel('Response to manager').fill('A second synthetic proof is now attached.')
  await page.getByRole('button', { name: 'Resubmit shared submission' }).click()
  await expect(page.getByRole('link', { name: 'synthetic-proof-one.txt' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'synthetic-proof-two.txt' })).toBeVisible()
  await captureEvidence(page, 'docker-step7', '09-second-attachment-resubmitted.png')

  await identity.selectOption('manager')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Manager' })).toBeVisible()
  await page.getByRole('button', { name: 'Review queue' }).click()
  await expect(page.getByRole('link', { name: 'synthetic-proof-one.txt' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'synthetic-proof-two.txt' })).toBeVisible()
  page.once('dialog', dialog => void dialog.accept())
  await page.getByRole('button', { name: 'Approve all 2' }).click()
  await expect(page.getByText('All caught up—nothing is waiting for review.')).toBeVisible()
  await captureEvidence(page, 'docker-step7', '10-manager-approved.png')

  await identity.selectOption('participant')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Participant' })).toBeVisible()
  await page.getByRole('button', { name: 'My activity' }).click()
  await expect(page.getByText('Approved', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Awarded task result: 25 XP')).toBeVisible()
  await expect(page.getByLabel('Submission history')).toContainText('Approved')
  await expect(page.getByRole('link', { name: 'synthetic-proof-one.txt' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'synthetic-proof-two.txt' })).toBeVisible()
  await captureEvidence(page, 'docker-step7', '11-participant-approved-25xp.png')
})
