import { expect, test } from '@playwright/test'
import { captureEvidence } from './evidence'

test('manager Scoresheet reconciles workflow XP and exposes append-only participant detail', async ({ page }) => {
  await page.goto('/')
  const identity = page.getByRole('combobox', { name: 'Demo identity' })
  await identity.selectOption('participant')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Participant' })).toBeVisible()
  const me = await page.request.get('/api/auth/me')
  expect(me.status()).toBe(200)
  const participantId = (await me.json()).participantId as string
  expect(participantId).toMatch(/^[0-9a-f-]{36}$/i)

  await page.getByRole('button', { name: 'Challenges' }).click()
  const task = page.locator('.task-row').filter({ hasText: 'Complete the synthetic shared task' })
  await task.getByRole('button', { name: 'Submit work' }).click()
  await page.getByRole('textbox', { name: 'Evidence *' }).fill('Synthetic Scoresheet acceptance evidence')
  await page.getByRole('button', { name: 'Submit for review' }).click()
  await expect(page.getByText('Submitted', { exact: true }).first()).toBeVisible()

  await identity.selectOption('manager')
  await page.getByRole('button', { name: 'Review queue' }).click()
  await expect(page.getByText('Synthetic Scoresheet acceptance evidence')).toBeVisible()
  page.once('dialog', dialog => void dialog.accept())
  await page.getByRole('button', { name: 'Approve all 2' }).click()
  await expect(page.getByText('All caught up—nothing is waiting for review.')).toBeVisible()

  const cyclesResponse = await page.request.get('/api/manager/reporting-cycles')
  expect(cyclesResponse.status()).toBe(200)
  const cycles = await cyclesResponse.json() as { defaultCycleId: string | null }
  expect(cycles.defaultCycleId, 'DETERMINISTIC_DEMO_SEED_REQUIRED: manager must have a reporting cycle').not.toBeNull()
  const cycleId = cycles.defaultCycleId!
  type SummaryRow = { participantId: string; displayName: string; participantStatus: string; totalXp: number; bySource: { taskApprovalXp: number; manualAwardXp: number; raidXp: number }; byEntryType: { netAdjustmentXp: number } }
  const getSummary = async () => {
    const response = await page.request.get(`/api/manager/scoresheet?cycleId=${cycleId}`)
    expect(response.status()).toBe(200)
    return await response.json() as { rows: SummaryRow[] }
  }
  const initialSummary = await getSummary()

  await page.getByRole('button', { name: 'Scoresheet' }).click()
  const cycleSelector = page.getByLabel('Scoresheet reporting cycle')
  await expect(cycleSelector).toHaveValue(cycleId)
  await expect(page.getByText('Cycle selection changes this Scoresheet reporting context.')).toBeVisible()
  const table = page.getByRole('table')
  await expect(table).toBeVisible()
  const participantRow = table.getByRole('row').filter({ hasText: 'Synthetic Participant' })
  const teammateRow = table.getByRole('row').filter({ hasText: 'Synthetic Teammate' })
  const managerRow = table.getByRole('row').filter({ hasText: 'Synthetic Manager' })
  for (const expected of initialSummary.rows) {
    const row = table.getByRole('row').filter({ hasText: expected.displayName })
    const cells = row.getByRole('cell')
    await expect(row).toBeVisible()
    await expect(cells.nth(1)).toHaveText(expected.participantStatus)
    await expect(cells.nth(2)).toHaveText(String(expected.bySource.taskApprovalXp))
    await expect(cells.nth(3)).toHaveText(String(expected.bySource.manualAwardXp))
    await expect(cells.nth(4)).toHaveText(String(expected.bySource.raidXp))
    await expect(cells.nth(5)).toHaveText(String(expected.byEntryType.netAdjustmentXp))
    await expect(cells.nth(6)).toHaveText(String(expected.totalXp))
  }
  expect(initialSummary.rows.every(row => ['Active', 'Withdrawn', 'Inactive'].includes(row.participantStatus))).toBe(true)
  expect(initialSummary.rows.some(row => row.totalXp === 0)).toBe(true)
  await expect(participantRow).toBeVisible()
  await expect(teammateRow).toBeVisible()
  await expect(managerRow).toBeVisible()
  await captureEvidence(page, 'docker-manager-scoresheet', '01-scoresheet-summary.png')
  await captureEvidence(page, 'docker-manager-scoresheet', '02-zero-xp-active-status.png')

  await participantRow.getByRole('button', { name: 'Synthetic Participant' }).click()
  const ledger = page.getByLabel('Participant Scoresheet detail')
  await expect(ledger).toBeVisible()
  await expect(ledger.getByText('+10 XP').first()).toBeVisible()
  await expect(ledger.getByText('Synthetic Shared Challenge · Complete the synthetic shared task').first()).toBeVisible()
  await expect(ledger.getByText('Synthetic Welcome Award')).toBeVisible()
  await expect(ledger.getByText(/Grant · ManualAward/).first()).toBeVisible()
  await expect(ledger.getByRole('button', { name: 'Load more' })).toHaveCount(0)
  const originalGrant = ledger.locator('article').filter({ hasText: '+25 XP' }).filter({ hasText: 'Grant · TaskApproval' }).first()
  await expect(originalGrant).toBeVisible()
  await expect(originalGrant.getByRole('button', { name: 'Correct XP' })).toBeVisible()
  await captureEvidence(page, 'docker-manager-scoresheet', '03-original-25-grant.png')

  await originalGrant.getByRole('button', { name: 'Correct XP' }).click()
  let dialog = page.getByRole('dialog', { name: 'Correct XP' })
  await expect(dialog.getByText('Current effective XP').locator('..')).toContainText('25 XP')
  const amount = dialog.getByLabel('New effective XP')
  await expect(amount).toHaveAttribute('min', '0')
  await expect(amount).toHaveAttribute('step', '1')
  await amount.fill('15')
  await dialog.getByLabel('Correction reason').fill('Synthetic downward correction to 15')
  await dialog.getByRole('button', { name: 'Review correction' }).click()
  await expect(dialog).toContainText('Original award+25 XP')
  await expect(dialog).toContainText('Current effective XP25 XP')
  await expect(dialog).toContainText('New effective XP15 XP')
  await expect(dialog).toContainText('Resulting change−10 XP')
  await expect(participantRow.getByRole('cell').last()).toHaveText(String(initialSummary.rows.find(row => row.participantId === participantId)!.totalXp))
  await captureEvidence(page, 'docker-manager-scoresheet', '04-confirm-25-to-15.png')
  await dialog.getByRole('button', { name: 'Confirm correction' }).click()
  await expect(page.getByText('XP correction recorded and authoritative Scoresheet data refreshed.')).toBeVisible()
  await expect(ledger.getByText('−10 XP').first()).toBeVisible()
  await expect(ledger.getByText('Synthetic downward correction to 15')).toBeVisible()
  await expect(originalGrant).toBeVisible()
  const reversal = ledger.locator('article').filter({ hasText: 'Synthetic downward correction to 15' })
  await expect(reversal.getByRole('button', { name: 'Correct XP' })).toHaveCount(0)
  await captureEvidence(page, 'docker-manager-scoresheet', '05-ledger-after-reversal.png')

  await originalGrant.getByRole('button', { name: 'Correct XP' }).click()
  dialog = page.getByRole('dialog', { name: 'Correct XP' })
  await expect(dialog.getByText('Current effective XP').locator('..')).toContainText('15 XP')
  await dialog.getByLabel('New effective XP').fill('20')
  await dialog.getByLabel('Correction reason').fill('Synthetic upward correction to 20')
  await dialog.getByRole('button', { name: 'Review correction' }).click()
  await expect(dialog).toContainText('Current effective XP15 XP')
  await expect(dialog).toContainText('New effective XP20 XP')
  await expect(dialog).toContainText('Resulting change+5 XP')
  await captureEvidence(page, 'docker-manager-scoresheet', '06-confirm-15-to-20.png')
  await dialog.getByRole('button', { name: 'Confirm correction' }).click()
  await expect(ledger.getByText('+5 XP').first()).toBeVisible()
  await expect(ledger.getByText('Synthetic upward correction to 20')).toBeVisible()
  await expect(originalGrant).toBeVisible()
  await expect(reversal).toBeVisible()
  const upward = ledger.locator('article').filter({ hasText: 'Synthetic upward correction to 20' })
  await expect(upward.getByRole('button', { name: 'Correct XP' })).toHaveCount(0)
  await captureEvidence(page, 'docker-manager-scoresheet', '07-ledger-after-correction.png')

  const finalSummary = await getSummary()
  const finalParticipant = finalSummary.rows.find(row => row.participantId === participantId)!
  const finalCells = participantRow.getByRole('cell')
  await expect(finalCells.nth(2)).toHaveText(String(finalParticipant.bySource.taskApprovalXp))
  await expect(finalCells.nth(5)).toHaveText(String(finalParticipant.byEntryType.netAdjustmentXp))
  await expect(finalCells.nth(6)).toHaveText(String(finalParticipant.totalXp))
  await captureEvidence(page, 'docker-manager-scoresheet', '08-final-scoresheet-total.png')

  await identity.selectOption('participant')
  await expect(page.getByRole('heading', { name: 'Welcome, Synthetic Participant' })).toBeVisible()
  await expect(page.getByText('Total XP', { exact: true }).locator('..')).toContainText(String(finalParticipant.totalXp))
  await page.getByRole('button', { name: 'XP Activity' }).click()
  await expect(page.getByText('+25 XP').first()).toBeVisible()
  await expect(page.getByText('−10 XP').first()).toBeVisible()
  await expect(page.getByText('+5 XP').first()).toBeVisible()
  await expect(page.getByText('Synthetic downward correction to 15')).toBeVisible()
  await expect(page.getByText('Synthetic upward correction to 20')).toBeVisible()
  await captureEvidence(page, 'docker-manager-scoresheet', '09-participant-corrected-activity.png')
  await page.getByRole('button', { name: 'Leaderboard' }).click()
  await expect(page.getByRole('heading', { name: 'Leaderboard', level: 2 })).toBeVisible()
  await expect(page.getByRole('row').filter({ hasText: 'Synthetic Participant' })).toContainText(`${finalParticipant.totalXp} XP`)
  await identity.selectOption('manager')
  await page.getByRole('button', { name: 'Review queue' }).click()
  await expect(page.getByText('All caught up—nothing is waiting for review.')).toBeVisible()
  await page.getByRole('button', { name: 'Challenges' }).click()
  await expect(page.getByRole('heading', { name: 'Challenge administration', level: 2 })).toBeVisible()
})
