// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.AIQuestPortal.Api.Data;

#nullable disable

namespace PAS.AIQuestPortal.Api.Data.Migrations
{
    [DbContext(typeof(QuestDbContext))]
    partial class QuestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.AwardCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_AwardCategories_GlobalCode")
                        .HasFilter("[CycleId] IS NULL");

                    b.HasIndex("CycleId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_AwardCategories_CycleCode")
                        .HasFilter("[CycleId] IS NOT NULL");

                    b.ToTable("AwardCategories", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CloseAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GuideCharacter")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeroImageReference")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OpenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByParticipantId");

                    b.HasIndex("CycleId");

                    b.ToTable("Challenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_Challenges_Dates", "[OpenAt] <= [DueAt] AND [DueAt] <= [CloseAt]");

                            t.HasCheckConstraint("CK_Challenges_Status", "[Status] IN ('Draft','Published','Open','Closed','Archived')");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeDeadlineChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ChangedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("NewDueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PreviousDueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersedesChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChallengeId", "SequenceNumber");

                    b.HasIndex("ChangedByParticipantId");

                    b.HasIndex("SupersedesChangeId")
                        .IsUnique()
                        .HasFilter("[SupersedesChangeId] IS NOT NULL");

                    b.HasIndex("ChallengeId", "ChangedAt");

                    b.HasIndex("SupersedesChangeId", "ChallengeId");

                    b.ToTable("ChallengeDeadlineChanges", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChallengeDeadlineChanges_Sequence", "[SequenceNumber] > 0");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ChallengeId");

                    b.HasIndex("CreatedByParticipantId");

                    b.HasIndex("ChallengeId", "CycleId");

                    b.ToTable("ChallengeParticipations", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeParticipationMember", b =>
                {
                    b.Property<Guid>("ChallengeParticipationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CycleTeamIdAtParticipation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedSnapshotAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ChallengeParticipationId", "ParticipantId");

                    b.HasIndex("CycleId", "ParticipantId");

                    b.HasIndex("CycleTeamIdAtParticipation", "CycleId")
                        .HasFilter("[CycleTeamIdAtParticipation] IS NOT NULL");

                    b.HasIndex("ParticipantId", "ChallengeId");

                    b.HasIndex("ChallengeParticipationId", "ChallengeId", "CycleId");

                    b.ToTable("ChallengeParticipationMembers", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomEvidenceRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenceRequirement")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScoringMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ChallengeTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChallengeTasks_EvidenceRequirement", "[EvidenceRequirement] IN ('None','Text','Link','Attachment','Multiple','Custom')");

                            t.HasCheckConstraint("CK_ChallengeTasks_ScoringMode", "[ScoringMode] IN ('Individual','WholeTeam','ClaimantSelectsBeneficiaries','AttendanceBased')");

                            t.HasCheckConstraint("CK_ChallengeTasks_XP", "[XP] >= 0");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeTeamPolicy", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSolo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("FormationDeadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FormationMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("LockAfterStart")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<int>("MinMembers")
                        .HasColumnType("int");

                    b.HasKey("ChallengeId");

                    b.ToTable("ChallengeTeamPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChallengeTeamPolicies_FormationMode", "[FormationMode] IN ('SelfForm','ManagerAssigned','Either')");

                            t.HasCheckConstraint("CK_ChallengeTeamPolicies_Size", "[MinMembers] > 0 AND [MaxMembers] > 0 AND [MinMembers] <= [MaxMembers]");

                            t.HasCheckConstraint("CK_ChallengeTeamPolicies_Solo", "[AllowSolo] = 1 OR [MinMembers] > 1");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ThemeConfiguration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByParticipantId");

                    b.ToTable("Cycles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cycles_DateRange", "[StartsAt] <= [EndsAt]");

                            t.HasCheckConstraint("CK_Cycles_Status", "[Status] IN ('Active','Closing','Finalised')");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RelatedXPEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersedesEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasAlternateKey("CycleId", "SequenceNumber");

                    b.HasIndex("ActorId");

                    b.HasIndex("CorrelationId")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("RelatedXPEntryId");

                    b.HasIndex("SupersedesEventId")
                        .IsUnique()
                        .HasFilter("[SupersedesEventId] IS NOT NULL");

                    b.HasIndex("SupersedesEventId", "CycleId");

                    b.HasIndex("CycleId", "OccurredAt", "Id");

                    b.ToTable("CycleEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_CycleEvents_Sequence", "[SequenceNumber] > 0");

                            t.HasCheckConstraint("CK_CycleEvents_StatusShape", "([EventType] = 'Created' AND [FromStatus] IS NULL AND [ToStatus] IS NOT NULL) OR ([EventType] IN ('StatusChanged','Reopened') AND [FromStatus] IS NOT NULL AND [ToStatus] IS NOT NULL AND [FromStatus] <> [ToStatus]) OR ([EventType] IN ('CorrectionAuthorised','CorrectionRecorded') AND [FromStatus] IS NULL AND [ToStatus] IS NULL)");

                            t.HasCheckConstraint("CK_CycleEvents_StatusValues", "([FromStatus] IS NULL OR [FromStatus] IN ('Active','Closing','Finalised')) AND ([ToStatus] IS NULL OR [ToStatus] IN ('Active','Closing','Finalised'))");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleParticipant", b =>
                {
                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("CycleId", "ParticipantId");

                    b.HasIndex("CycleId", "Status");

                    b.HasIndex("ParticipantId", "CycleId");

                    b.ToTable("CycleParticipants", null, t =>
                        {
                            t.HasCheckConstraint("CK_CycleParticipants_Dates", "[LeftAt] IS NULL OR [JoinedAt] IS NULL OR [LeftAt] >= [JoinedAt]");

                            t.HasCheckConstraint("CK_CycleParticipants_Status", "[Status] IN ('Active','Withdrawn','Inactive')");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "Name")
                        .IsUnique();

                    b.ToTable("CycleTeams", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("UX_CycleTeamMembers_OpenMembership")
                        .HasFilter("[LeftAt] IS NULL");

                    b.HasIndex("CycleTeamId", "CycleId");

                    b.HasIndex("CycleTeamId", "ParticipantId", "JoinedAt")
                        .IsUnique();

                    b.ToTable("CycleTeamMembers", null, t =>
                        {
                            t.HasCheckConstraint("CK_CycleTeamMembers_Dates", "[LeftAt] IS NULL OR [LeftAt] >= [JoinedAt]");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasFilter("[EntraObjectId] IS NOT NULL");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ParticipantChallengeDeadlineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("NewEffectiveDueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NewOverrideDueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PreviousEffectiveDueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PreviousOverrideDueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersedesEventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChallengeId", "ParticipantId", "SequenceNumber");

                    b.HasIndex("ActorId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SupersedesEventId")
                        .IsUnique()
                        .HasFilter("[SupersedesEventId] IS NOT NULL");

                    b.HasIndex("SupersedesEventId", "ChallengeId", "ParticipantId");

                    b.HasIndex("ChallengeId", "ParticipantId", "OccurredAt", "Id");

                    b.ToTable("ParticipantChallengeDeadlineEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_ParticipantDeadlineEvents_Sequence", "[SequenceNumber] > 0");

                            t.HasCheckConstraint("CK_ParticipantDeadlineEvents_Shape", "([EventType] = 'OverrideCleared' AND [NewOverrideDueAt] IS NULL) OR ([EventType] IN ('OverrideSet','OverrideChanged') AND [NewOverrideDueAt] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.RaidEntitlement", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PassType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("AssignedCount")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId", "CycleId", "PassType");

                    b.HasIndex("CycleId", "ParticipantId");

                    b.ToTable("RaidEntitlements", null, t =>
                        {
                            t.HasCheckConstraint("CK_RaidEntitlements_AssignedCount", "[AssignedCount] >= 0");

                            t.HasCheckConstraint("CK_RaidEntitlements_PassType", "[PassType] IN ('Physical','Remote')");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.RaidParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PassType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("RaidSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "ParticipantId");

                    b.HasIndex("RaidSessionId", "CycleId");

                    b.HasIndex("ParticipantId", "RaidSessionId", "PassType")
                        .IsUnique();

                    b.ToTable("RaidParticipations", null, t =>
                        {
                            t.HasCheckConstraint("CK_RaidParticipations_PassType", "[PassType] IN ('Physical','Remote')");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.RaidSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("RaidSessions", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChallengeParticipationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReviewerComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "CycleId");

                    b.HasIndex("ClaimantId", "SubmittedAt");

                    b.HasIndex("CycleId", "ClaimantId");

                    b.HasIndex("Status", "SubmittedAt");

                    b.HasIndex("TaskId", "ChallengeId");

                    b.HasIndex("ChallengeParticipationId", "ChallengeId", "CycleId");

                    b.ToTable("Submissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Submissions_Status", "[Status] IN ('Submitted','UnderReview','NeedsEvidence','Resubmitted','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.SubmissionBeneficiary", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AddedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubmissionId", "ParticipantId");

                    b.HasAlternateKey("SubmissionId", "ParticipantId", "CycleId");

                    b.HasIndex("AddedByParticipantId");

                    b.HasIndex("CycleId", "ParticipantId");

                    b.HasIndex("SubmissionId", "CycleId");

                    b.ToTable("SubmissionBeneficiaries", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.SubmissionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("SubmissionId", "OccurredAt", "Id");

                    b.ToTable("SubmissionEvents", (string)null);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.SubmissionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Container")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EvidenceKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProvidedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageAccount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProvidedByParticipantId");

                    b.HasIndex("SubmissionId", "CreatedAt");

                    b.ToTable("SubmissionEvidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubmissionEvidence_Shape", "([EvidenceKind] = 'Text' AND [TextValue] IS NOT NULL AND [LinkUrl] IS NULL AND [BlobKey] IS NULL) OR ([EvidenceKind] = 'Link' AND [LinkUrl] IS NOT NULL AND [TextValue] IS NULL AND [BlobKey] IS NULL) OR ([EvidenceKind] = 'Attachment' AND [StorageAccount] IS NOT NULL AND [Container] IS NOT NULL AND [BlobKey] IS NOT NULL AND [OriginalFileName] IS NOT NULL AND [MimeType] IS NOT NULL AND [SizeBytes] IS NOT NULL AND [SizeBytes] >= 0 AND [TextValue] IS NULL AND [LinkUrl] IS NULL)");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.XPEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AwardCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AwardedByParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChallengeParticipationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CycleTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RaidSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AwardedByParticipantId");

                    b.HasIndex("ChallengeParticipationId");

                    b.HasIndex("ReversesEntryId");

                    b.HasIndex("AwardCategoryId", "CycleId");

                    b.HasIndex("ChallengeId", "TaskId");

                    b.HasIndex("CycleId", "ParticipantId");

                    b.HasIndex("CycleTeamId", "CycleId");

                    b.HasIndex("RaidSessionId", "CycleId");

                    b.HasIndex("RaidSessionId", "ParticipantId");

                    b.HasIndex("SubmissionId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("UX_XPEntries_TaskApprovalGrant_Submission_Participant")
                        .HasFilter("[EntryType] = 'Grant' AND [SourceType] = 'TaskApproval'");

                    b.HasIndex("ChallengeParticipationId", "ChallengeId", "CycleId");

                    b.HasIndex("ReversesEntryId", "ParticipantId", "CycleId", "SourceType");

                    b.HasIndex("SubmissionId", "ChallengeId", "TaskId", "CycleId");

                    b.ToTable("XPEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_XPEntries_AmountAndReversal", "([EntryType] = 'Grant' AND [ReversesEntryId] IS NULL AND [Amount] > 0) OR ([EntryType] = 'Reversal' AND [ReversesEntryId] IS NOT NULL AND [Amount] < 0) OR ([EntryType] = 'Correction' AND [ReversesEntryId] IS NOT NULL AND [Amount] > 0)");

                            t.HasCheckConstraint("CK_XPEntries_ParticipationChallenge", "[ChallengeParticipationId] IS NULL OR [ChallengeId] IS NOT NULL");

                            t.HasCheckConstraint("CK_XPEntries_SourceShape", "([SourceType] = 'TaskApproval' AND [SubmissionId] IS NOT NULL AND [ChallengeId] IS NOT NULL AND [TaskId] IS NOT NULL AND [AwardCategoryId] IS NULL AND [RaidSessionId] IS NULL) OR ([SourceType] = 'ManualAward' AND [AwardCategoryId] IS NOT NULL AND [SubmissionId] IS NULL AND [TaskId] IS NULL AND [RaidSessionId] IS NULL) OR ([SourceType] = 'Raid' AND [RaidSessionId] IS NOT NULL AND [AwardCategoryId] IS NULL AND [SubmissionId] IS NULL AND [TaskId] IS NULL)");
                        });
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.AwardCategory", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.Challenge", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeDeadlineChange", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("ChangedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.ChallengeDeadlineChange", null)
                        .WithMany()
                        .HasForeignKey("SupersedesChangeId", "ChallengeId")
                        .HasPrincipalKey("Id", "ChallengeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeParticipation", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeParticipationMember", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleParticipant", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleTeam", null)
                        .WithMany()
                        .HasForeignKey("CycleTeamIdAtParticipation", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.ChallengeParticipation", null)
                        .WithMany()
                        .HasForeignKey("ChallengeParticipationId", "ChallengeId", "CycleId")
                        .HasPrincipalKey("Id", "ChallengeId", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeTask", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ChallengeTeamPolicy", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Challenge", null)
                        .WithOne()
                        .HasForeignKey("PAS.AIQuestPortal.Api.Data.ChallengeTeamPolicy", "ChallengeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.Cycle", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleEvent", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.XPEntry", null)
                        .WithMany()
                        .HasForeignKey("RelatedXPEntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleEvent", null)
                        .WithMany()
                        .HasForeignKey("SupersedesEventId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleParticipant", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleTeam", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.CycleTeamMember", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleParticipant", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleTeam", null)
                        .WithMany()
                        .HasForeignKey("CycleTeamId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.ParticipantChallengeDeadlineEvent", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.ParticipantChallengeDeadlineEvent", null)
                        .WithMany()
                        .HasForeignKey("SupersedesEventId", "ChallengeId", "ParticipantId")
                        .HasPrincipalKey("Id", "ChallengeId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.RaidEntitlement", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleParticipant", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.RaidParticipation", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleParticipant", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.RaidSession", null)
                        .WithMany()
                        .HasForeignKey("RaidSessionId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.RaidSession", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.Submission", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleParticipant", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "ClaimantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.ChallengeTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId", "ChallengeId")
                        .HasPrincipalKey("Id", "ChallengeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.ChallengeParticipation", null)
                        .WithMany()
                        .HasForeignKey("ChallengeParticipationId", "ChallengeId", "CycleId")
                        .HasPrincipalKey("Id", "ChallengeId", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.SubmissionBeneficiary", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("AddedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleParticipant", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.SubmissionEvent", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.SubmissionEvidence", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("ProvidedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PAS.AIQuestPortal.Api.Data.XPEntry", b =>
                {
                    b.HasOne("PAS.AIQuestPortal.Api.Data.AwardCategory", null)
                        .WithMany()
                        .HasForeignKey("AwardCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Participant", null)
                        .WithMany()
                        .HasForeignKey("AwardedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleParticipant", null)
                        .WithMany()
                        .HasForeignKey("CycleId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PAS.AIQuestPortal.Api.Data.CycleTeam", null)
                        .WithMany()
                        .HasForeignKey("CycleTeamId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.RaidSession", null)
                        .WithMany()
                        .HasForeignKey("RaidSessionId", "CycleId")
                        .HasPrincipalKey("Id", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.SubmissionBeneficiary", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.ChallengeParticipation", null)
                        .WithMany()
                        .HasForeignKey("ChallengeParticipationId", "ChallengeId", "CycleId")
                        .HasPrincipalKey("Id", "ChallengeId", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.XPEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId", "ParticipantId", "CycleId", "SourceType")
                        .HasPrincipalKey("Id", "ParticipantId", "CycleId", "SourceType")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PAS.AIQuestPortal.Api.Data.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId", "ChallengeId", "TaskId", "CycleId")
                        .HasPrincipalKey("Id", "ChallengeId", "TaskId", "CycleId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
