import { useCallback, useEffect, useRef, useState } from 'react'
import { RaidAdminApiError, raidError, type RaidAdminApi } from './raidAdminApi'
import type { RaidCycle, RaidParticipant, RaidPassBalance, RaidPassType, RaidSession } from './types'

const two = (n: number) => String(n).padStart(2, '0')
const localInput = (value: string) => { const d = new Date(value); return `${d.getFullYear()}-${two(d.getMonth() + 1)}-${two(d.getDate())}T${two(d.getHours())}:${two(d.getMinutes())}` }
const localToUtc = (value: string) => new Date(value).toISOString()
const displayDate = (value: string) => new Date(value).toLocaleString()
const newRequestId = () => crypto.randomUUID()
type SessionForm = { name: string; occurredAt: string }
type Action = { kind: 'pass'; participant: RaidParticipant; passType: RaidPassType } | { kind: 'participation'; participant: RaidParticipant } | { kind: 'xp'; participant: RaidParticipant }
type PendingRaidXp = { requestId: string; participantId: string; participantName: string; raidSessionId: string; raidSessionName: string; amount: number; reason: string }

export function RaidAdministration({ api }: { api: RaidAdminApi }) {
  const [cycles, setCycles] = useState<RaidCycle[]>([]), [cycleId, setCycleId] = useState(''), [sessions, setSessions] = useState<RaidSession[]>([]), [sessionId, setSessionId] = useState(''), [projection, setProjection] = useState<{ raid: RaidSession; participants: RaidParticipant[] } | null>(null)
  const [cyclesLoading, setCyclesLoading] = useState(true), [sessionsLoading, setSessionsLoading] = useState(false), [participantsLoading, setParticipantsLoading] = useState(false), [error, setError] = useState<string | null>(null), [success, setSuccess] = useState<string | null>(null)
  const [sessionMode, setSessionMode] = useState<'create' | 'edit' | null>(null), [sessionForm, setSessionForm] = useState<SessionForm>({ name: '', occurredAt: '' }), [timestampBaseline, setTimestampBaseline] = useState<{ server: string; local: string } | null>(null), [action, setAction] = useState<Action | null>(null), [pendingRaidXp, setPendingRaidXp] = useState<PendingRaidXp | null>(null)
  const cyclesGen = useRef(0), sessionsGen = useRef(0), participantsGen = useRef(0), viewGen = useRef(0), cycleRef = useRef(''), sessionRef = useRef(''), triggerRef = useRef<HTMLElement | null>(null)
  useEffect(() => { cycleRef.current = cycleId }, [cycleId]); useEffect(() => { sessionRef.current = sessionId }, [sessionId])
  const loadCycles = useCallback(async () => { const gen = ++cyclesGen.current; setCyclesLoading(true); setError(null); try { const result = await api.getCycles(); if (gen === cyclesGen.current) { setCycles(result.cycles); setCycleId((current) => current || result.defaultCycleId || result.cycles[0]?.id || '') } } catch (e) { if (gen === cyclesGen.current) setError(raidError(e)) } finally { if (gen === cyclesGen.current) setCyclesLoading(false) } }, [api])
  const loadSessions = useCallback(async (id: string) => { const gen = ++sessionsGen.current; ++participantsGen.current; ++viewGen.current; setSessionsLoading(true); setError(null); setSessions([]); setSessionId(''); setProjection(null); setAction(null); setSessionMode(null); try { const result = await api.getSessions(id); if (gen === sessionsGen.current && cycleRef.current === id) setSessions(result.raids) } catch (e) { if (gen === sessionsGen.current && cycleRef.current === id) setError(raidError(e)) } finally { if (gen === sessionsGen.current && cycleRef.current === id) setSessionsLoading(false) } }, [api])
  const loadParticipants = useCallback(async (id: string) => { const gen = ++participantsGen.current; setParticipantsLoading(true); setError(null); setProjection(null); try { const result = await api.getParticipants(id); if (gen === participantsGen.current && sessionRef.current === id) setProjection(result) } catch (e) { if (gen === participantsGen.current && sessionRef.current === id) setError(raidError(e)) } finally { if (gen === participantsGen.current && sessionRef.current === id) setParticipantsLoading(false) } }, [api])
  useEffect(() => { void loadCycles() }, [loadCycles]); useEffect(() => { if (cycleId) void loadSessions(cycleId) }, [cycleId, loadSessions]); useEffect(() => { if (sessionId) void loadParticipants(sessionId) }, [sessionId, loadParticipants])
  const selectSession = (id: string) => { ++participantsGen.current; ++viewGen.current; setAction(null); setSessionMode(null); setSessionId(id); if (id === sessionId) void loadParticipants(id) }
  const refreshCurrent = async (mutCycle: string, mutSession?: string) => { const result = await api.getSessions(mutCycle); if (cycleRef.current !== mutCycle) return; setSessions(result.raids); if (mutSession && sessionRef.current === mutSession) await loadParticipants(mutSession) }
  const openCreate = () => { ++participantsGen.current; ++viewGen.current; triggerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setSessionMode('create'); setSessionForm({ name: '', occurredAt: '' }); setTimestampBaseline(null); setError(null) }
  const openEdit = () => { if (!projection) return; ++viewGen.current; triggerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; const local = localInput(projection.raid.occurredAt); setSessionMode('edit'); setSessionForm({ name: projection.raid.name, occurredAt: local }); setTimestampBaseline({ server: projection.raid.occurredAt, local }); setError(null) }
  const closeOverlay = () => { setSessionMode(null); setAction(null); queueMicrotask(() => triggerRef.current?.focus()) }
  const openAction = (next: Action) => { triggerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setAction(next); setError(null) }
  const selectedCycle = cycles.find((cycle) => cycle.id === cycleId), activeViewGeneration = viewGen.current
  return <section className="raid-admin"><header className="section-heading"><p className="eyebrow">MANAGER</p><h2>Raid Administration</h2><p>Manage Raid Sessions, pass resources, participation, and separately audited Raid XP.</p></header>
    {success && <div className="success-notice" role="status">{success}</div>}{error && !sessionMode && !action && <State error text={error} retry={() => cycleId ? void loadSessions(cycleId) : void loadCycles()} />}
    {cyclesLoading ? <State text="Loading Raid cycles…" /> : !cycles.length ? <State text="No reporting cycles are available." /> : <><label className="field raid-cycle-select"><span>Reporting cycle</span><select value={cycleId} onChange={(e) => setCycleId(e.target.value)}>{cycles.map((cycle) => <option value={cycle.id} key={cycle.id}>{cycle.name} · {cycle.code} · {cycle.status}</option>)}</select><small>Reporting context only; this does not change challenge eligibility.</small></label>
      <div className="raid-layout"><section className="raid-sessions"><header><div><p className="eyebrow">RAID SESSIONS</p><h3>{selectedCycle?.name}</h3></div>{selectedCycle && selectedCycle.status !== 'Finalised' && <button className="button" onClick={openCreate}>Create Raid Session</button>}</header>{sessionsLoading ? <State text="Loading Raid Sessions…" /> : !sessions.length ? <State text="No Raid Sessions exist for this cycle." /> : sessions.map((session) => <button className={session.id === sessionId ? 'raid-session raid-session--selected' : 'raid-session'} key={session.id} onClick={() => selectSession(session.id)}><strong>{session.name}</strong><span>{displayDate(session.occurredAt)}</span><small>{session.hasReferences ? 'Read-only · referenced' : session.allowedActions.canEdit ? 'Editable' : 'Read-only'}</small></button>)}</section>
      <section className="raid-detail">{!sessionId ? <State text="Select a Raid Session to manage participant passes and actions." /> : participantsLoading ? <State text="Loading Raid participants…" /> : projection ? <><header className="raid-detail__header"><div><p className="eyebrow">SELECTED RAID SESSION</p><h3>{projection.raid.name}</h3><p>{displayDate(projection.raid.occurredAt)} · {projection.raid.cycleStatus}</p></div>{projection.raid.allowedActions.canEdit && <button className="button button--quiet" onClick={openEdit}>Edit Raid Session</button>}</header><div className="raid-separation"><strong>RAID PASS ≠ XP</strong><span>Pass assignment and use do not award XP. Raid XP is a separate audited ledger action.</span></div>{!projection.participants.length ? <State text="No participants are enrolled in this cycle." /> : <div className="raid-participants">{projection.participants.map((participant) => <ParticipantCard key={participant.participantId} participant={participant} raid={projection.raid} onAction={openAction} />)}</div>}</> : null}</section></div></>}
    {sessionMode && selectedCycle && <SessionDialog mode={sessionMode} cycle={selectedCycle} session={projection?.raid ?? null} form={sessionForm} setForm={setSessionForm} baseline={timestampBaseline} api={api} onError={setError} error={error} onClose={closeOverlay} onReload={async () => { if (!projection) return; try { const authoritative = await api.getSession(projection.raid.id); if (viewGen.current !== activeViewGeneration || sessionRef.current !== authoritative.id) return; const local = localInput(authoritative.occurredAt); setProjection((current) => current && current.raid.id === authoritative.id ? { ...current, raid: authoritative } : current); setSessions((current) => current.map((item) => item.id === authoritative.id ? authoritative : item)); setSessionForm({ name: authoritative.name, occurredAt: local }); setTimestampBaseline({ server: authoritative.occurredAt, local }) } catch (e) { if (viewGen.current === activeViewGeneration) setError(raidError(e)) } }} onSaved={async (saved) => { if (viewGen.current !== activeViewGeneration || cycleRef.current !== saved.cycleId || (sessionMode === 'edit' && sessionRef.current !== saved.id)) return; setSessionMode(null); setSuccess(sessionMode === 'create' ? 'Raid Session created.' : 'Raid Session updated.'); setSessionId(saved.id); await refreshCurrent(saved.cycleId, saved.id) }} />}
    {action && projection && <ActionDialog action={action} raid={projection.raid} api={api} error={error} setError={setError} pendingRaidXp={pendingRaidXp} onFreezeRaidXp={setPendingRaidXp} onClearRaidXp={() => setPendingRaidXp(null)} onClose={closeOverlay} onAuthoritativeConflict={async (message) => { const cycle = projection.raid.cycleId, session = projection.raid.id; if (viewGen.current !== activeViewGeneration || cycleRef.current !== cycle || sessionRef.current !== session) return; await loadParticipants(session); if (viewGen.current === activeViewGeneration && cycleRef.current === cycle && sessionRef.current === session) { setAction(null); setError(message) } }} onSuccess={async (message) => { const cycle = projection.raid.cycleId, session = projection.raid.id; if (viewGen.current !== activeViewGeneration || cycleRef.current !== cycle || sessionRef.current !== session) return; setAction(null); setSuccess(message); await loadParticipants(session) }} />}
  </section>
}

function ParticipantCard({ participant, raid, onAction }: { participant: RaidParticipant; raid: RaidSession; onAction: (action: Action) => void }) { return <article className="raid-participant"><header><div><h4>{participant.displayName}</h4><span className="participant-status">{participant.cycleParticipantStatus}</span></div>{participant.participation ? <p>Participation: <strong>{participant.participation.passType}</strong> · {displayDate(participant.participation.usedAt)}</p> : <p>Participation: <strong>None</strong></p>}</header><div className="raid-pass-grid"><Balance label="Physical" value={participant.physical} action={participant.allowedActions.canManagePasses ? () => onAction({ kind: 'pass', participant, passType: 'Physical' }) : undefined} /><Balance label="Remote" value={participant.remote} action={participant.allowedActions.canManagePasses ? () => onAction({ kind: 'pass', participant, passType: 'Remote' }) : undefined} /></div><div className="raid-card-actions">{participant.allowedActions.canRecordParticipation && !participant.participation && <button className="button button--quiet" onClick={() => onAction({ kind: 'participation', participant })}>Record Raid Participation</button>}{participant.allowedActions.canAwardXp && <button className="button button--warning" onClick={() => onAction({ kind: 'xp', participant })}>Award Raid XP</button>}{!participant.allowedActions.canManagePasses && !participant.allowedActions.canRecordParticipation && !participant.allowedActions.canAwardXp && <span className="muted">Read-only</span>}<span className="sr-only">Session {raid.name}</span></div></article> }
function Balance({ label, value, action }: { label: RaidPassType; value: RaidPassBalance; action?: () => void }) { return <section aria-label={`${label} pass`}><strong>{label}</strong><dl><div><dt>Assigned</dt><dd>{value.assigned}</dd></div><div><dt>Used</dt><dd>{value.used}</dd></div><div><dt>Remaining</dt><dd>{value.remaining}</dd></div></dl>{action && <button onClick={action}>Update {label} assignment</button>}</section> }

function SessionDialog({ mode, cycle, session, form, setForm, baseline, api, error, onError, onClose, onReload, onSaved }: { mode: 'create' | 'edit'; cycle: RaidCycle; session: RaidSession | null; form: SessionForm; setForm: React.Dispatch<React.SetStateAction<SessionForm>>; baseline: { server: string; local: string } | null; api: RaidAdminApi; error: string | null; onError: (v: string | null) => void; onClose: () => void; onReload: () => Promise<void>; onSaved: (session: RaidSession) => Promise<void> }) {
  const [pending, setPending] = useState(false); const save = async () => { if (!form.name.trim() || form.name.trim().length > 200 || !form.occurredAt) return onError('Enter a session name of 200 characters or fewer and an occurrence time.'); setPending(true); onError(null); try { const occurredAt = baseline && form.occurredAt === baseline.local ? baseline.server : localToUtc(form.occurredAt); const saved = mode === 'create' ? await api.createSession({ cycleId: cycle.id, name: form.name.trim(), occurredAt }) : await api.updateSession(session!.id, { rowVersion: session!.rowVersion, name: form.name.trim(), occurredAt }); await onSaved(saved) } catch (e) { const message = raidError(e); onError(message); if (e instanceof RaidAdminApiError && e.code === 'RaidSessionImmutable') { await onReload(); onClose() } } finally { setPending(false) } }
  return <Dialog title={mode === 'create' ? 'Create Raid Session' : 'Edit Raid Session'} pending={pending} onClose={onClose}><p>Cycle: <strong>{cycle.name} · {cycle.code}</strong></p><label className="field"><span>Name</span><input autoFocus maxLength={200} value={form.name} onChange={(e) => setForm((v) => ({ ...v, name: e.target.value }))} /></label><label className="field"><span>Occurred At</span><input type="datetime-local" value={form.occurredAt} onChange={(e) => setForm((v) => ({ ...v, occurredAt: e.target.value }))} /></label>{error && <p className="inline-error" role="alert">{error}{error.includes('changed') && <button type="button" onClick={() => void onReload()}>Reload authoritative session</button>}</p>}<div className="form-actions"><button className="button button--quiet" onClick={onClose} disabled={pending}>Cancel</button><button className="button" onClick={() => void save()} disabled={pending}>{pending ? 'Saving…' : 'Save Raid Session'}</button></div></Dialog>
}

function ActionDialog({ action, raid, api, error, setError, pendingRaidXp, onFreezeRaidXp, onClearRaidXp, onClose, onAuthoritativeConflict, onSuccess }: { action: Action; raid: RaidSession; api: RaidAdminApi; error: string | null; setError: (v: string | null) => void; pendingRaidXp: PendingRaidXp | null; onFreezeRaidXp: (intent: PendingRaidXp) => void; onClearRaidXp: () => void; onClose: () => void; onAuthoritativeConflict: (message: string) => Promise<void>; onSuccess: (message: string) => Promise<void> }) {
  const [pending, setPending] = useState(false), [assigned, setAssigned] = useState(action.kind === 'pass' ? String(action.participant[action.passType.toLowerCase() as 'physical' | 'remote'].assigned) : ''), [passType, setPassType] = useState<RaidPassType>('Physical'), [amount, setAmount] = useState(''), [reason, setReason] = useState(''), [confirming, setConfirming] = useState(false), [requestId, setRequestId] = useState(newRequestId)
  const participant = action.participant; const balance = (type: RaidPassType) => participant[type.toLowerCase() as 'physical' | 'remote']; const reviewXp = () => { const n = Number(amount); if (!Number.isInteger(n) || n <= 0) return setError('Enter a positive whole-number XP amount.'); if (!reason.trim()) return setError('Enter a reason for the Raid XP award.'); if (reason.trim().length > 2000) return setError('Reason must be 2,000 characters or fewer.'); setError(null); setConfirming(true) }
  const matchingPending = action.kind === 'xp' && pendingRaidXp?.participantId === participant.participantId && pendingRaidXp.raidSessionId === raid.id ? pendingRaidXp : null
  const conflictingPending = action.kind === 'xp' && pendingRaidXp && !matchingPending ? pendingRaidXp : null
  const submit = async () => { if (pending) return; setPending(true); setError(null); try { if (action.kind === 'pass') { const count = Number(assigned); if (!Number.isInteger(count) || count < 0) throw new Error('Assigned count must be a non-negative whole number.'); const b = balance(action.passType); await api.updateEntitlement(raid.cycleId, participant.participantId, action.passType, count, b.entitlementRowVersion); await onSuccess(`${action.passType} pass assignment refreshed.`) } else if (action.kind === 'participation') { await api.recordParticipation(raid.id, participant.participantId, passType); await onSuccess('Raid participation recorded. Pass usage refreshed; no XP was awarded.') } else { const intent = matchingPending ?? { requestId, participantId: participant.participantId, participantName: participant.displayName, raidSessionId: raid.id, raidSessionName: raid.name, amount: Number(amount), reason: reason.trim() }; if (!matchingPending) onFreezeRaidXp(intent); await api.awardXp(raid.id, { requestId: intent.requestId, participantId: intent.participantId, amount: intent.amount, reason: intent.reason }); onClearRaidXp(); setRequestId(newRequestId()); await onSuccess('Raid XP recorded. Updated XP is available in Scoresheet and participant reporting.') } } catch (e) { const message = e instanceof RaidAdminApiError ? raidError(e) : e instanceof Error ? e.message : raidError(e); if (action.kind === 'pass' && e instanceof RaidAdminApiError && (e.code === 'RaidEntitlementVersionConflict' || e.code === 'RaidEntitlementBelowUsed')) await onAuthoritativeConflict(message); else setError(message) } finally { setPending(false) } }
  if (action.kind === 'pass') return <Dialog title={`Update ${action.passType} assignment`} pending={pending} onClose={onClose}><p>{participant.displayName}</p><p>Used is authoritative and cannot be edited: <strong>{balance(action.passType).used}</strong></p><label className="field"><span>Assigned</span><input autoFocus type="number" min="0" step="1" value={assigned} onChange={(e) => setAssigned(e.target.value)} /></label>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button onClick={onClose} disabled={pending}>Cancel</button><button className="button" onClick={() => void submit()} disabled={pending}>{pending ? 'Saving…' : 'Save assignment'}</button></div></Dialog>
  if (action.kind === 'participation') { const choices = (['Physical', 'Remote'] as const).filter((type) => balance(type).remaining > 0), effectivePassType = choices.includes(passType) ? passType : choices[0] ?? 'Physical', chosen = balance(effectivePassType); const record = async () => { setPassType(effectivePassType); if (pending) return; setPending(true); setError(null); try { await api.recordParticipation(raid.id, participant.participantId, effectivePassType); await onSuccess('Raid participation recorded. Pass usage refreshed; no XP was awarded.') } catch (e) { setError(raidError(e)) } finally { setPending(false) } }; return <Dialog title="Record Raid Participation" pending={pending} onClose={onClose}><dl><div><dt>Participant</dt><dd>{participant.displayName}</dd></div><div><dt>Raid Session</dt><dd>{raid.name}</dd></div></dl><label className="field"><span>Pass type</span><select autoFocus value={effectivePassType} onChange={(e) => setPassType(e.target.value as RaidPassType)}>{choices.map((type) => <option key={type}>{type}</option>)}</select></label><p>Assigned {chosen.assigned} · Used {chosen.used} · Remaining {chosen.remaining}</p>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button onClick={onClose} disabled={pending}>Cancel</button><button className="button" onClick={() => void record()} disabled={pending || !choices.length}>{pending ? 'Recording…' : 'Confirm participation'}</button></div></Dialog> }
  const resetAward = () => { if (matchingPending || conflictingPending) onClearRaidXp(); setRequestId(newRequestId()); setAmount(''); setReason(''); setConfirming(false); setError(null) }
  if (conflictingPending) return <Dialog title="Pending Raid XP award" pending={pending} onClose={onClose}><p>A previous Raid XP attempt remains pending for <strong>{conflictingPending.participantName}</strong> in <strong>{conflictingPending.raidSessionName}</strong>.</p><p className="shared-note">Its request identifier will not be reused in this participant or Raid Session. Explicitly abandon it before starting another award.</p><div className="form-actions"><button onClick={onClose}>Keep pending award</button><button className="button button--warning" onClick={resetAward}>Abandon and start new award</button></div></Dialog>
  const shownAmount = matchingPending?.amount ?? Number(amount), shownReason = matchingPending?.reason ?? reason.trim(), retrying = Boolean(matchingPending)
  return <Dialog title="Award Raid XP" pending={pending} onClose={onClose}>{!confirming && !retrying ? <><p>{participant.displayName} · {raid.name}</p><p className="shared-note">Raid XP is a separate audited ledger award. It does not assign or use a Raid pass.</p><label className="field"><span>XP amount</span><input autoFocus type="number" min="1" step="1" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label className="field"><span>Reason</span><textarea maxLength={2000} value={reason} onChange={(e) => setReason(e.target.value)} /></label>{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button onClick={onClose}>Close</button><button onClick={resetAward}>Reset / New award</button><button className="button" onClick={reviewXp}>Review Raid XP</button></div></> : <><h4>{retrying ? 'Retry audited Raid XP' : 'Confirm audited Raid XP'}</h4><dl><div><dt>Participant</dt><dd>{participant.displayName}</dd></div><div><dt>Raid Session</dt><dd>{raid.name}</dd></div><div><dt>XP</dt><dd>+{shownAmount} XP</dd></div><div><dt>Reason</dt><dd>{shownReason}</dd></div></dl>{retrying && <p className="shared-note">This attempted award is frozen. Retry resends the exact same command and request identifier.</p>}{error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button onClick={onClose} disabled={pending}>Close</button>{retrying ? <button onClick={resetAward} disabled={pending}>Abandon and start new award</button> : <button onClick={() => setConfirming(false)} disabled={pending}>Back</button>}<button className="button button--warning" onClick={() => void submit()} disabled={pending}>{pending ? 'Awarding…' : retrying ? 'Retry same award' : 'Confirm Raid XP'}</button></div></>}</Dialog>
}

function Dialog({ title, pending, onClose, children }: { title: string; pending: boolean; onClose: () => void; children: React.ReactNode }) { const ref = useRef<HTMLElement>(null); useEffect(() => { ref.current?.querySelector<HTMLElement>('input, select, textarea, button:not(:disabled)')?.focus() }, []); const key = (e: React.KeyboardEvent) => { if (e.key === 'Escape' && !pending) { e.preventDefault(); onClose() } if (e.key === 'Tab') { const controls = [...(ref.current?.querySelectorAll<HTMLElement>('input:not(:disabled), select:not(:disabled), textarea:not(:disabled), button:not(:disabled)') ?? [])]; if (!controls.length) return; const first = controls[0], last = controls[controls.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus() } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus() } } }; return <div className="cycle-modal-backdrop"><section ref={ref} className="cycle-action raid-dialog" role="dialog" aria-modal="true" aria-labelledby="raid-dialog-title" onKeyDown={key}><h3 id="raid-dialog-title">{title}</h3>{children}</section></div> }
function State({ text, error, retry }: { text: string; error?: boolean; retry?: () => void }) { return <div className={error ? 'workflow-state workflow-state--error' : 'workflow-state'} role={error ? 'alert' : 'status'}><p>{text}</p>{retry && <button className="button button--quiet" onClick={retry}>Retry</button>}</div> }
