import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { RaidAdministration } from './RaidAdministration'
import { RaidAdminApiError, type RaidAdminApi } from './raidAdminApi'
import type { RaidCycle, RaidParticipant, RaidParticipantList, RaidSession } from './types'

afterEach(() => { cleanup(); vi.unstubAllEnvs() })
const cycle = (id = 'c1', status: RaidCycle['status'] = 'Active'): RaidCycle => ({ id, code: id.toUpperCase(), name: `Cycle ${id.toUpperCase()}`, status, startsAt: '2026-08-01T00:00:00Z', endsAt: '2026-08-31T00:00:00Z' })
const session = (id = 'r1', cycleId = 'c1', overrides: Partial<RaidSession> = {}): RaidSession => ({ id, cycleId, cycleName: `Cycle ${cycleId.toUpperCase()}`, cycleStatus: 'Active', name: `Raid ${id.toUpperCase()}`, occurredAt: '2026-08-10T00:00:30.500Z', rowVersion: `${id}-version`, hasReferences: false, allowedActions: { canEdit: true, canManagePasses: true, canRecordParticipation: true, canAwardXp: true }, ...overrides })
const participant = (overrides: Partial<RaidParticipant> = {}): RaidParticipant => ({ participantId: 'p1', displayName: 'Avery Demo', cycleParticipantStatus: 'Active', physical: { assigned: 2, used: 1, remaining: 1, entitlementRowVersion: 'physical-v1' }, remote: { assigned: 1, used: 0, remaining: 1, entitlementRowVersion: 'remote-v1' }, participation: null, allowedActions: { canManagePasses: true, canRecordParticipation: true, canAwardXp: true }, ...overrides })
const projection = (raid = session(), people = [participant()]): RaidParticipantList => ({ raid, participants: people })
function service(overrides: Partial<RaidAdminApi> = {}): RaidAdminApi { return { getCycles: vi.fn().mockResolvedValue({ defaultCycleId: 'c1', cycles: [cycle()] }), getSessions: vi.fn().mockResolvedValue({ cycle: cycle(), raids: [session()] }), getSession: vi.fn().mockResolvedValue(session()), getParticipants: vi.fn().mockResolvedValue(projection()), createSession: vi.fn().mockResolvedValue(session('new')), updateSession: vi.fn().mockResolvedValue(session()), updateEntitlement: vi.fn().mockResolvedValue({}), recordParticipation: vi.fn().mockResolvedValue({}), awardXp: vi.fn().mockResolvedValue({}), ...overrides } as RaidAdminApi }
const deferred = <T,>() => { let resolve!: (value: T) => void; let reject!: (reason: unknown) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no }); return { promise, resolve, reject } }
async function openParticipant(api = service()) { const user = userEvent.setup(); render(<RaidAdministration api={api} />); await user.click(await screen.findByRole('button', { name: /Raid R1/ })); await screen.findByRole('heading', { name: 'Avery Demo' }); return { user, api } }

describe('Raid Administration', () => {
  it('uses the default cycle and suppresses a stale sessions response after cycle switching', async () => {
    const a = deferred<{ cycle: RaidCycle; raids: RaidSession[] }>(), b = deferred<{ cycle: RaidCycle; raids: RaidSession[] }>(), getSessions = vi.fn((id: string) => id === 'c1' ? a.promise : b.promise), api = service({ getCycles: vi.fn().mockResolvedValue({ defaultCycleId: 'c1', cycles: [cycle('c1'), cycle('c2')] }), getSessions }); const user = userEvent.setup(); render(<RaidAdministration api={api} />)
    await waitFor(() => expect(getSessions).toHaveBeenCalledWith('c1')); await user.selectOptions(screen.getByRole('combobox', { name: /Reporting cycle/ }), 'c2'); b.resolve({ cycle: cycle('c2'), raids: [session('r2', 'c2')] }); expect(await screen.findByRole('button', { name: /Raid R2/ })).toBeInTheDocument(); await act(async () => { a.resolve({ cycle: cycle('c1'), raids: [session('r1')] }); await a.promise }); expect(screen.queryByRole('button', { name: /Raid R1/ })).not.toBeInTheDocument()
  })

  it('suppresses stale participant detail when a newer session is selected', async () => {
    const a = deferred<RaidParticipantList>(), b = deferred<RaidParticipantList>(), api = service({ getSessions: vi.fn().mockResolvedValue({ cycle: cycle(), raids: [session('r1'), session('r2')] }), getParticipants: vi.fn((id: string) => id === 'r1' ? a.promise : b.promise) }); const user = userEvent.setup(); render(<RaidAdministration api={api} />); await user.click(await screen.findByRole('button', { name: /Raid R1/ })); await user.click(screen.getByRole('button', { name: /Raid R2/ })); b.resolve(projection(session('r2'), [participant({ displayName: 'Morgan Demo' })])); expect(await screen.findByRole('heading', { name: 'Morgan Demo' })).toBeInTheDocument(); await act(async () => { a.resolve(projection(session('r1'))); await a.promise }); expect(screen.queryByRole('heading', { name: 'Avery Demo' })).not.toBeInTheDocument()
  })

  it('creates a Raid Session with validation and refreshes authoritative selection', async () => {
    const created = session('new'), api = service({ createSession: vi.fn().mockResolvedValue(created), getSessions: vi.fn().mockResolvedValueOnce({ cycle: cycle(), raids: [] }).mockResolvedValue({ cycle: cycle(), raids: [created] }), getParticipants: vi.fn().mockResolvedValue(projection(created)) }); const user = userEvent.setup(); render(<RaidAdministration api={api} />); await user.click(await screen.findByRole('button', { name: 'Create Raid Session' })); await user.click(screen.getByRole('button', { name: 'Save Raid Session' })); expect(await screen.findByRole('alert')).toHaveTextContent('200 characters'); await user.type(screen.getByLabelText('Name'), 'Monday Raid'); fireEvent.change(screen.getByLabelText('Occurred At'), { target: { value: '2026-08-20T18:30' } }); await user.click(screen.getByRole('button', { name: 'Save Raid Session' })); await waitFor(() => expect(api.createSession).toHaveBeenCalledWith({ cycleId: 'c1', name: 'Monday Raid', occurredAt: new Date('2026-08-20T18:30').toISOString() })); expect(await screen.findByText('Raid Session created.')).toBeInTheDocument()
  })

  it('preserves Create fields when an already-started participant response completes late', async () => {
    const oldProjection = deferred<RaidParticipantList>(), getParticipants = vi.fn().mockReturnValue(oldProjection.promise), createSession = vi.fn().mockResolvedValue(session('new')), api = service({ getParticipants, createSession }); const user = userEvent.setup(); render(<RaidAdministration api={api} />); await user.click(await screen.findByRole('button', { name: /Raid R1/ })); await waitFor(() => expect(getParticipants).toHaveBeenCalledTimes(1)); expect(getParticipants).toHaveBeenCalledWith('r1'); await user.click(screen.getByRole('button', { name: 'Create Raid Session' })); await user.type(screen.getByLabelText('Name'), 'Race-safe Raid'); fireEvent.change(screen.getByLabelText('Occurred At'), { target: { value: '2026-09-02T18:45' } }); expect(screen.getByLabelText('Name')).toHaveValue('Race-safe Raid'); expect(screen.getByLabelText('Occurred At')).toHaveValue('2026-09-02T18:45'); await act(async () => { oldProjection.resolve(projection(session('r1', 'c1', { name: 'Stale Raid', occurredAt: '2026-01-01T01:02:03.400Z' }))); await oldProjection.promise }); expect(screen.getByRole('dialog', { name: 'Create Raid Session' })).toBeInTheDocument(); expect(screen.getByLabelText('Name')).toHaveValue('Race-safe Raid'); expect(screen.getByLabelText('Occurred At')).toHaveValue('2026-09-02T18:45'); await user.click(screen.getByRole('button', { name: 'Save Raid Session' })); await waitFor(() => expect(createSession).toHaveBeenCalledWith({ cycleId: 'c1', name: 'Race-safe Raid', occurredAt: new Date('2026-09-02T18:45').toISOString() }))
  })

  it('keeps Finalised cycles fully read-only using server action flags', async () => {
    const finalRaid = session('r1', 'c1', { cycleStatus: 'Finalised', allowedActions: { canEdit: false, canManagePasses: false, canRecordParticipation: false, canAwardXp: false } }), person = participant({ allowedActions: { canManagePasses: false, canRecordParticipation: false, canAwardXp: false } }), api = service({ getCycles: vi.fn().mockResolvedValue({ defaultCycleId: 'c1', cycles: [cycle('c1', 'Finalised')] }), getSessions: vi.fn().mockResolvedValue({ cycle: cycle('c1', 'Finalised'), raids: [finalRaid] }), getParticipants: vi.fn().mockResolvedValue(projection(finalRaid, [person])) }); await openParticipant(api); for (const action of ['Create Raid Session', 'Edit Raid Session', 'Record Raid Participation', 'Award Raid XP', 'Update Physical assignment']) expect(screen.queryByRole('button', { name: action })).not.toBeInTheDocument(); expect(screen.getAllByText('Read-only').length).toBeGreaterThan(0)
  })

  it('preserves an exact unchanged timestamp and converts a changed Sydney local timestamp', async () => {
    vi.stubEnv('TZ', 'Australia/Sydney'); const precise = session(), updateSession = vi.fn().mockResolvedValue(precise), api = service({ updateSession }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Edit Raid Session' })); expect(screen.getByLabelText('Occurred At')).toHaveValue('2026-08-10T10:00'); await user.clear(screen.getByLabelText('Name')); await user.type(screen.getByLabelText('Name'), 'Metadata only'); await user.click(screen.getByRole('button', { name: 'Save Raid Session' })); await waitFor(() => expect(updateSession).toHaveBeenLastCalledWith('r1', { rowVersion: 'r1-version', name: 'Metadata only', occurredAt: '2026-08-10T00:00:30.500Z' })); await user.click(await screen.findByRole('button', { name: 'Edit Raid Session' })); fireEvent.change(screen.getByLabelText('Occurred At'), { target: { value: '2026-08-11T09:15' } }); await user.click(screen.getByRole('button', { name: 'Save Raid Session' })); await waitFor(() => expect(updateSession).toHaveBeenLastCalledWith('r1', expect.objectContaining({ occurredAt: '2026-08-10T23:15:00.000Z' })))
  })

  it('maps stale session version without silent retry and offers authoritative reload', async () => {
    const updateSession = vi.fn().mockRejectedValue(new RaidAdminApiError(409, 'RaidSessionVersionConflict', 'raw')); const { user } = await openParticipant(service({ updateSession })); await user.click(screen.getByRole('button', { name: 'Edit Raid Session' })); await user.click(screen.getByRole('button', { name: 'Save Raid Session' })); expect(await screen.findByRole('alert')).toHaveTextContent('changed'); expect(screen.getByRole('button', { name: 'Reload authoritative session' })).toBeInTheDocument(); expect(updateSession).toHaveBeenCalledTimes(1)
  })

  it('reloads authoritative immutable session state and removes Edit', async () => { const immutable = session('r1', 'c1', { hasReferences: true, allowedActions: { canEdit: false, canManagePasses: true, canRecordParticipation: true, canAwardXp: true } }), updateSession = vi.fn().mockRejectedValue(new RaidAdminApiError(409, 'RaidSessionImmutable', 'raw')), getSession = vi.fn().mockResolvedValue(immutable), api = service({ updateSession, getSession }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Edit Raid Session' })); await user.click(screen.getByRole('button', { name: 'Save Raid Session' })); expect(await screen.findByRole('alert')).toHaveTextContent('can no longer be edited'); expect(getSession).toHaveBeenCalledWith('r1'); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Edit Raid Session' })).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: /Raid R1/ })).toHaveTextContent('referenced') })

  it.each(['Physical', 'Remote'] as const)('creates or updates %s entitlement with its authoritative rowVersion', async (passType) => {
    const api = service(); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: `Update ${passType} assignment` })); const assigned = screen.getByLabelText('Assigned'); await user.clear(assigned); await user.type(assigned, '3'); await user.click(screen.getByRole('button', { name: 'Save assignment' })); const balance = participant()[passType.toLowerCase() as 'physical' | 'remote']; await waitFor(() => expect(api.updateEntitlement).toHaveBeenCalledWith('c1', 'p1', passType, 3, balance.entitlementRowVersion)); expect(api.getParticipants).toHaveBeenCalledTimes(2)
  })

  it('creates a missing entitlement with a null rowVersion and permits zero assignment', async () => {
    const person = participant({ physical: { assigned: 0, used: 0, remaining: 0, entitlementRowVersion: null } }), api = service({ getParticipants: vi.fn().mockResolvedValue(projection(session(), [person])) }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Update Physical assignment' })); await user.click(screen.getByRole('button', { name: 'Save assignment' })); await waitFor(() => expect(api.updateEntitlement).toHaveBeenCalledWith('c1', 'p1', 'Physical', 0, null))
  })

  it.each([['RaidEntitlementBelowUsed', 'cannot be lower'], ['RaidEntitlementVersionConflict', 'changed']] as const)('shows safe pass assignment error for %s', async (code, text) => {
    const api = service({ updateEntitlement: vi.fn().mockRejectedValue(new RaidAdminApiError(409, code, 'raw')) }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Update Physical assignment' })); await user.click(screen.getByRole('button', { name: 'Save assignment' })); expect(await screen.findByRole('alert')).toHaveTextContent(text)
  })

  it('refreshes a stale entitlement and uses the new rowVersion on explicit resubmission', async () => { const stale = participant(), refreshed = participant({ physical: { assigned: 4, used: 2, remaining: 2, entitlementRowVersion: 'physical-v2' } }), getParticipants = vi.fn().mockResolvedValueOnce(projection(session(), [stale])).mockResolvedValue(projection(session(), [refreshed])), updateEntitlement = vi.fn().mockRejectedValueOnce(new RaidAdminApiError(409, 'RaidEntitlementVersionConflict', 'raw')).mockResolvedValue({}), api = service({ getParticipants, updateEntitlement }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Update Physical assignment' })); await user.click(screen.getByRole('button', { name: 'Save assignment' })); expect(await screen.findByRole('alert')).toHaveTextContent('changed'); expect(getParticipants).toHaveBeenCalledTimes(2); const physical = screen.getByRole('region', { name: 'Physical pass' }); expect(within(within(physical).getByText('Assigned').parentElement!).getByText('4')).toBeInTheDocument(); expect(within(within(physical).getByText('Used').parentElement!).getByText('2')).toBeInTheDocument(); expect(within(within(physical).getByText('Remaining').parentElement!).getByText('2')).toBeInTheDocument(); await user.click(within(physical).getByRole('button', { name: 'Update Physical assignment' })); const input = screen.getByLabelText('Assigned'); expect(input).toHaveValue(4); await user.clear(input); await user.type(input, '5'); await user.click(screen.getByRole('button', { name: 'Save assignment' })); await waitFor(() => expect(updateEntitlement).toHaveBeenLastCalledWith('c1', 'p1', 'Physical', 5, 'physical-v2')) })

  it('refreshes newer Used/Remaining after below-used conflict and discards stale dialog values', async () => { const stale = participant(), refreshed = participant({ physical: { assigned: 3, used: 3, remaining: 0, entitlementRowVersion: 'physical-v3' } }), getParticipants = vi.fn().mockResolvedValueOnce(projection(session(), [stale])).mockResolvedValue(projection(session(), [refreshed])), api = service({ getParticipants, updateEntitlement: vi.fn().mockRejectedValue(new RaidAdminApiError(409, 'RaidEntitlementBelowUsed', 'raw')) }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Update Physical assignment' })); await user.click(screen.getByRole('button', { name: 'Save assignment' })); expect(await screen.findByRole('alert')).toHaveTextContent('cannot be lower'); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); const physical = screen.getByRole('region', { name: 'Physical pass' }); expect(within(within(physical).getByText('Assigned').parentElement!).getByText('3')).toBeInTheDocument(); expect(within(within(physical).getByText('Used').parentElement!).getByText('3')).toBeInTheDocument(); expect(within(within(physical).getByText('Remaining').parentElement!).getByText('0')).toBeInTheDocument() })

  it.each(['Physical', 'Remote'] as const)('records %s participation and refreshes Used/Remaining without awarding XP', async (passType) => {
    const before = participant(), after = participant({ physical: passType === 'Physical' ? { ...before.physical, used: 2, remaining: 0 } : before.physical, remote: passType === 'Remote' ? { ...before.remote, used: 1, remaining: 0 } : before.remote, participation: { participationId: 'use1', participantId: 'p1', cycleId: 'c1', raidSessionId: 'r1', passType, usedAt: '2026-08-20T00:00:00Z' } }), getParticipants = vi.fn().mockResolvedValueOnce(projection(session(), [before])).mockResolvedValue(projection(session(), [after])), api = service({ getParticipants }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Record Raid Participation' })); await user.selectOptions(screen.getByLabelText('Pass type'), passType); await user.click(screen.getByRole('button', { name: 'Confirm participation' })); await waitFor(() => expect(api.recordParticipation).toHaveBeenCalledWith('r1', 'p1', passType)); expect(await screen.findByText('Raid participation recorded. Pass usage refreshed; no XP was awarded.')).toBeInTheDocument(); expect(api.awardXp).not.toHaveBeenCalled(); expect(screen.getByText(passType, { selector: '.raid-participant header strong' })).toBeInTheDocument()
  })

  it('shows participation conflict and does not pretend success', async () => { const api = service({ recordParticipation: vi.fn().mockRejectedValue(new RaidAdminApiError(409, 'RaidParticipationConflict', 'raw')) }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Record Raid Participation' })); await user.click(screen.getByRole('button', { name: 'Confirm participation' })); expect(await screen.findByRole('alert')).toHaveTextContent('conflicts'); expect(screen.queryByText(/participation recorded/)).not.toBeInTheDocument() })

  it('validates, confirms, and records participant-specific Raid XP separately from passes', async () => {
    const api = service(); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); expect(await screen.findByRole('alert')).toHaveTextContent('positive whole-number'); await user.type(screen.getByLabelText('XP amount'), '15'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); expect(screen.getByRole('alert')).toHaveTextContent('reason'); await user.type(screen.getByLabelText('Reason'), 'Monday raid award'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); const dialog = screen.getByRole('dialog'); expect(dialog).toHaveTextContent('Avery Demo'); expect(dialog).toHaveTextContent('Raid R1'); expect(dialog).toHaveTextContent('+15 XP'); await user.click(screen.getByRole('button', { name: 'Confirm Raid XP' })); await waitFor(() => expect(api.awardXp).toHaveBeenCalledWith('r1', expect.objectContaining({ participantId: 'p1', amount: 15, reason: 'Monday raid award', requestId: expect.any(String) }))); expect(await screen.findByText(/Updated XP is available in Scoresheet/)).toBeInTheDocument(); expect(api.updateEntitlement).not.toHaveBeenCalled(); expect(api.recordParticipation).not.toHaveBeenCalled()
  })

  it.each(['0', '-1', '1.5'])('blocks invalid Raid XP amount %s', async (value) => { const { user, api } = await openParticipant(); await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); await user.type(screen.getByLabelText('XP amount'), value); await user.type(screen.getByLabelText('Reason'), 'Invalid amount'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); expect(await screen.findByRole('alert')).toHaveTextContent('positive whole-number'); expect(api.awardXp).not.toHaveBeenCalled() })

  it('blocks a Raid XP reason over 2,000 characters', async () => { const { user, api } = await openParticipant(); await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); await user.type(screen.getByLabelText('XP amount'), '10'); fireEvent.change(screen.getByLabelText('Reason'), { target: { value: 'x'.repeat(2001) } }); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); expect(await screen.findByRole('alert')).toHaveTextContent('2,000'); expect(api.awardXp).not.toHaveBeenCalled() })

  it('retains a frozen attempted award across close/reopen, retries it exactly, and uses a new ID after success', async () => {
    const awardXp = vi.fn().mockRejectedValueOnce(new RaidAdminApiError(503, 'RaidAdministrationDependencyUnavailable', 'Unavailable')).mockResolvedValue({}), api = service({ awardXp }); const { user } = await openParticipant(api); const award = async (amount = '10', reason = 'Retry-safe award') => { await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); await user.type(screen.getByLabelText('XP amount'), amount); await user.type(screen.getByLabelText('Reason'), reason); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); await user.click(screen.getByRole('button', { name: 'Confirm Raid XP' })) }; await award(); expect(await screen.findByRole('alert')).toHaveTextContent('Unavailable'); expect(screen.queryByLabelText('XP amount')).not.toBeInTheDocument(); expect(screen.queryByLabelText('Reason')).not.toBeInTheDocument(); expect(screen.getByText(/attempted award is frozen/)).toBeInTheDocument(); const originalCall = awardXp.mock.calls[0]; await user.click(screen.getByRole('button', { name: 'Close' })); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); expect(screen.getByText(/attempted award is frozen/)).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Retry same award' })); await waitFor(() => expect(awardXp).toHaveBeenCalledTimes(2)); expect(awardXp.mock.calls[1]).toEqual(originalCall); const firstId = originalCall[1].requestId; await screen.findByText(/Updated XP/); await award('12', 'New intentional award'); await waitFor(() => expect(awardXp).toHaveBeenCalledTimes(3)); expect(awardXp.mock.calls[2][1]).toEqual(expect.objectContaining({ amount: 12, reason: 'New intentional award' })); expect(awardXp.mock.calls[2][1].requestId).not.toBe(firstId)
  })

  it('explicit abandonment discards a frozen command, generates a new requestId, and re-enables editing', async () => { const awardXp = vi.fn().mockRejectedValue(new RaidAdminApiError(503, 'RaidAdministrationDependencyUnavailable', 'Unavailable')), api = service({ awardXp }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); await user.type(screen.getByLabelText('XP amount'), '10'); await user.type(screen.getByLabelText('Reason'), 'First intent'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); await user.click(screen.getByRole('button', { name: 'Confirm Raid XP' })); await screen.findByRole('alert'); const firstId = awardXp.mock.calls[0][1].requestId; await user.click(screen.getByRole('button', { name: 'Close' })); await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); await user.click(screen.getByRole('button', { name: 'Abandon and start new award' })); expect(screen.getByLabelText('XP amount')).toHaveValue(null); await user.type(screen.getByLabelText('XP amount'), '20'); await user.type(screen.getByLabelText('Reason'), 'Second intent'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); await user.click(screen.getByRole('button', { name: 'Confirm Raid XP' })); await waitFor(() => expect(awardXp).toHaveBeenCalledTimes(2)); expect(awardXp.mock.calls[1][1]).toEqual(expect.objectContaining({ amount: 20, reason: 'Second intent' })); expect(awardXp.mock.calls[1][1].requestId).not.toBe(firstId) })

  it('does not reuse a pending intent in another participant context', async () => { const blake = participant({ participantId: 'p2', displayName: 'Blake Demo' }), awardXp = vi.fn().mockRejectedValue(new RaidAdminApiError(503, 'RaidAdministrationDependencyUnavailable', 'Unavailable')), api = service({ awardXp, getParticipants: vi.fn().mockResolvedValue(projection(session(), [participant(), blake])) }); const { user } = await openParticipant(api); const averyCard = screen.getByRole('heading', { name: 'Avery Demo' }).closest('article')!; await user.click(within(averyCard).getByRole('button', { name: 'Award Raid XP' })); await user.type(screen.getByLabelText('XP amount'), '10'); await user.type(screen.getByLabelText('Reason'), 'Avery intent'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); await user.click(screen.getByRole('button', { name: 'Confirm Raid XP' })); await screen.findByRole('alert'); const oldId = awardXp.mock.calls[0][1].requestId; await user.click(screen.getByRole('button', { name: 'Close' })); const blakeCard = screen.getByRole('heading', { name: 'Blake Demo' }).closest('article')!; await user.click(within(blakeCard).getByRole('button', { name: 'Award Raid XP' })); expect(screen.getByRole('dialog', { name: 'Pending Raid XP award' })).toHaveTextContent('Avery Demo'); expect(screen.queryByLabelText('XP amount')).not.toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Abandon and start new award' })); await user.type(screen.getByLabelText('XP amount'), '8'); await user.type(screen.getByLabelText('Reason'), 'Blake intent'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); await user.click(screen.getByRole('button', { name: 'Confirm Raid XP' })); await waitFor(() => expect(awardXp).toHaveBeenCalledTimes(2)); expect(awardXp.mock.calls[1][1]).toEqual(expect.objectContaining({ participantId: 'p2', amount: 8, reason: 'Blake intent' })); expect(awardXp.mock.calls[1][1].requestId).not.toBe(oldId) })

  it('keeps Raid XP conflict explicit and exposes no actions for inactive participants', async () => {
    const inactive = participant({ cycleParticipantStatus: 'Inactive', allowedActions: { canManagePasses: false, canRecordParticipation: false, canAwardXp: false } }), api = service({ getParticipants: vi.fn().mockResolvedValue(projection(session(), [inactive])) }); await openParticipant(api); expect(screen.getByText('Inactive')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Award Raid XP' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Record Raid Participation' })).not.toBeInTheDocument()
  })

  it('maps Raid XP request conflict and never automatically retries', async () => { const awardXp = vi.fn().mockRejectedValue(new RaidAdminApiError(409, 'RaidXpRequestConflict', 'raw')), api = service({ awardXp }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Award Raid XP' })); await user.type(screen.getByLabelText('XP amount'), '5'); await user.type(screen.getByLabelText('Reason'), 'Conflict test'); await user.click(screen.getByRole('button', { name: 'Review Raid XP' })); await user.click(screen.getByRole('button', { name: 'Confirm Raid XP' })); expect(await screen.findByRole('alert')).toHaveTextContent('request identifier conflicts'); expect(awardXp).toHaveBeenCalledTimes(1) })

  it('moves focus into dialogs, closes on Escape, and restores the invoking control', async () => { const { user } = await openParticipant(); const trigger = screen.getByRole('button', { name: 'Award Raid XP' }); trigger.focus(); await user.click(trigger); expect(screen.getByLabelText('XP amount')).toHaveFocus(); await user.keyboard('{Escape}'); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); await waitFor(() => expect(trigger).toHaveFocus()) })

  it('does not let an old mutation completion reselect its cycle or session', async () => {
    const save = deferred<unknown>(), api = service({ getCycles: vi.fn().mockResolvedValue({ defaultCycleId: 'c1', cycles: [cycle('c1'), cycle('c2')] }), getSessions: vi.fn((id: string) => Promise.resolve({ cycle: cycle(id), raids: [session(id === 'c1' ? 'r1' : 'r2', id)] })), getParticipants: vi.fn((id: string) => Promise.resolve(projection(session(id, id === 'r1' ? 'c1' : 'c2')))), updateEntitlement: vi.fn().mockReturnValue(save.promise) }); const { user } = await openParticipant(api); await user.click(screen.getByRole('button', { name: 'Update Physical assignment' })); await user.click(screen.getByRole('button', { name: 'Save assignment' })); await user.selectOptions(screen.getByRole('combobox', { name: /Reporting cycle/ }), 'c2'); expect(await screen.findByRole('button', { name: /Raid R2/ })).toBeInTheDocument(); await act(async () => { save.resolve({}); await save.promise }); expect(screen.queryByRole('button', { name: /Raid R1/ })).not.toBeInTheDocument()
  })
})
