using System.Buffers.Binary;
using System.IO.Compression;
using System.Text;
using System.Text.RegularExpressions;
using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Sas;
using Microsoft.Extensions.Options;
using PAS.AIQuestPortal.Api.Configuration;
using PAS.AIQuestPortal.Api.Workflow;

namespace PAS.AIQuestPortal.Api.Evidence;

public sealed record EvidenceBlobWrite(string BlobKey, Stream Content, string MimeType);
public sealed record EvidenceBlobRead(Stream Content, string MimeType, long SizeBytes);
public sealed record EvidenceReadAccess(EvidenceBlobRead? Stream, Uri? RedirectUri, string OriginalFileName);
public interface IEvidenceBlobStore { Task PutAsync(EvidenceBlobWrite write,CancellationToken ct); Task<EvidenceBlobRead> OpenReadAsync(string key,CancellationToken ct); Task<EvidenceReadAccess> CreateReadAccessAsync(string key,string mime,long size,string name,CancellationToken ct); Task DeleteUncommittedAsync(string key,CancellationToken ct); }
public interface IEvidenceBlobStoreInitializer { Task EnsurePrivateContainerAsync(CancellationToken ct); }

public sealed class AzureEvidenceBlobStore(BlobServiceClient service,IOptions<StorageOptions> options):IEvidenceBlobStore,IEvidenceBlobStoreInitializer
{
    public const string ContainerName="quest-evidence"; private readonly BlobContainerClient container=service.GetBlobContainerClient(ContainerName);
    public async Task EnsurePrivateContainerAsync(CancellationToken ct){await container.CreateIfNotExistsAsync(PublicAccessType.None,cancellationToken:ct);BlobContainerProperties p=(await container.GetPropertiesAsync(cancellationToken:ct)).Value;if(p.PublicAccess!=PublicAccessType.None){await container.SetAccessPolicyAsync(PublicAccessType.None,cancellationToken:ct);p=(await container.GetPropertiesAsync(cancellationToken:ct)).Value;if(p.PublicAccess!=PublicAccessType.None)throw new InvalidOperationException("Evidence container public access could not be disabled.");}}
    public async Task PutAsync(EvidenceBlobWrite w,CancellationToken ct)=>await container.GetBlobClient(w.BlobKey).UploadAsync(w.Content,new BlobUploadOptions{HttpHeaders=new BlobHttpHeaders{ContentType=w.MimeType}},ct);
    public async Task<EvidenceBlobRead> OpenReadAsync(string key,CancellationToken ct){Response<BlobDownloadStreamingResult> r=await container.GetBlobClient(key).DownloadStreamingAsync(cancellationToken:ct);return new(r.Value.Content,r.Value.Details.ContentType??"application/octet-stream",r.Value.Details.ContentLength);}
    public async Task<EvidenceReadAccess> CreateReadAccessAsync(string key,string mime,long size,string name,CancellationToken ct){if(!string.IsNullOrWhiteSpace(options.Value.ConnectionString))return new(await OpenReadAsync(key,ct),null,name);DateTimeOffset start=DateTimeOffset.UtcNow.AddMinutes(-1),end=DateTimeOffset.UtcNow.AddMinutes(5);Response<UserDelegationKey> delegation=await service.GetUserDelegationKeyAsync(start,end,ct);return new(null,container.GetBlobClient(key).GenerateUserDelegationSasUri(CreateReadSas(key,mime,name,start,end),delegation.Value),name);}
    public async Task DeleteUncommittedAsync(string key,CancellationToken ct)=>await container.GetBlobClient(key).DeleteIfExistsAsync(DeleteSnapshotsOption.IncludeSnapshots,cancellationToken:ct);
    public static BlobSasBuilder CreateReadSas(string key,string mime,string name,DateTimeOffset start,DateTimeOffset end){var sas=new BlobSasBuilder{BlobContainerName=ContainerName,BlobName=key,Resource="b",StartsOn=start,ExpiresOn=end,ContentType=mime,ContentDisposition=$"attachment; filename*=UTF-8''{Uri.EscapeDataString(name)}"};sas.SetPermissions(BlobSasPermissions.Read);return sas;}
}

public enum MalwareScanResult{Clean,Detected,Failed} public interface IEvidenceMalwareScanner{Task<MalwareScanResult> ScanAsync(Stream content,CancellationToken ct);} public sealed class DeterministicPassThroughEvidenceMalwareScanner:IEvidenceMalwareScanner{public Task<MalwareScanResult> ScanAsync(Stream content,CancellationToken ct)=>Task.FromResult(MalwareScanResult.Clean);} public sealed class DisabledEvidenceMalwareScanner:IEvidenceMalwareScanner{public Task<MalwareScanResult> ScanAsync(Stream content,CancellationToken ct)=>Task.FromResult(MalwareScanResult.Failed);}

public sealed class AttachmentUpload(string fileKey,string label,string originalFileName,string declaredMimeType,string temporaryPath,long sizeBytes):IAsyncDisposable
{
    public string FileKey{get;}=fileKey;public string Label{get;}=label;public string OriginalFileName{get;}=originalFileName;public string DeclaredMimeType{get;}=declaredMimeType;public string TemporaryPath{get;}=temporaryPath;public long SizeBytes{get;}=sizeBytes;
    public Stream OpenRead()=>new FileStream(TemporaryPath,FileMode.Open,FileAccess.Read,FileShare.Read,65536,FileOptions.Asynchronous|FileOptions.SequentialScan);public ValueTask DisposeAsync(){try{File.Delete(TemporaryPath);}catch{}return ValueTask.CompletedTask;}
}
public sealed record ValidatedAttachment(Guid EvidenceId,string Label,string OriginalFileName,string MimeType,string TemporaryPath,long SizeBytes){public Stream OpenRead()=>new FileStream(TemporaryPath,FileMode.Open,FileAccess.Read,FileShare.Read,65536,FileOptions.Asynchronous|FileOptions.SequentialScan);}

public sealed class EvidenceAttachmentValidator(IOptions<StorageOptions> storage,IEvidenceMalwareScanner scanner)
{
    private const int MaxEntries=256,MaxTypes=262144;private const long MaxEntry=26214400,MaxTotal=67108864;private const double MaxRatio=100;
    private sealed record Rule(string Mime,Func<Stream,long,bool> Match);private static readonly Dictionary<string,Rule> Rules=new(StringComparer.OrdinalIgnoreCase){[".jpg"]=new("image/jpeg",Jpeg),[".jpeg"]=new("image/jpeg",Jpeg),[".png"]=new("image/png",Png),[".webp"]=new("image/webp",Webp),[".pdf"]=new("application/pdf",Pdf),[".txt"]=new("text/plain",Text),[".docx"]=new("application/vnd.openxmlformats-officedocument.wordprocessingml.document",(s,l)=>Office(s,"word/document.xml","application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml")),[".xlsx"]=new("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",(s,l)=>Office(s,"xl/workbook.xml","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml")),[".pptx"]=new("application/vnd.openxmlformats-officedocument.presentationml.presentation",(s,l)=>Office(s,"ppt/presentation.xml","application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml")),[".mp4"]=new("video/mp4",Mp4)};
    public async Task<IReadOnlyList<ValidatedAttachment>> ValidateAsync(IReadOnlyList<AttachmentUpload> files,CancellationToken ct){EvidenceAttachmentOptions limits=storage.Value.Evidence;if(!limits.Enabled&&files.Count>0)throw E(400,"InvalidMultipartEvidence","Attachment evidence is disabled.");if(files.Count>limits.MaxAttachmentsPerRequest)throw E(413,"TooManyAttachments","Too many attachments.");if(files.Sum(x=>x.SizeBytes)>limits.MaxBytesPerRequest)throw E(413,"AttachmentRequestTooLarge","Combined attachment size is too large.");var result=new List<ValidatedAttachment>();foreach(AttachmentUpload f in files){if(f.SizeBytes==0)throw E(400,"InvalidMultipartEvidence","Empty attachments are not allowed.");if(f.SizeBytes>limits.MaxBytesPerFile)throw E(413,"AttachmentTooLarge","An attachment is too large.");string name=NormalizeFileName(f.OriginalFileName),ext=Path.GetExtension(name).ToLowerInvariant(),declared=f.DeclaredMimeType.Split(';',2)[0].Trim().ToLowerInvariant();if(!Rules.TryGetValue(ext,out Rule? rule)||declared!=rule.Mime)throw E(415,"AttachmentTypeNotAllowed","Attachment type is not allowed.");bool match;try{await using Stream input=f.OpenRead();match=rule.Match(input,f.SizeBytes);}catch(Exception x)when(x is InvalidDataException or IOException or EndOfStreamException){match=false;}if(!match)throw E(415,"AttachmentTypeMismatch","Attachment content does not match its type.");await using Stream scan=f.OpenRead();MalwareScanResult scanResult=await scanner.ScanAsync(scan,ct);if(scanResult==MalwareScanResult.Detected)throw E(422,"MalwareDetected","Malware was detected.");if(scanResult==MalwareScanResult.Failed)throw E(503,"MalwareScanUnavailable","Malware scanning is unavailable.");result.Add(new(Guid.NewGuid(),f.Label.Trim(),name,rule.Mime,f.TemporaryPath,f.SizeBytes));}return result;}
    public static string NormalizeFileName(string value){string leaf=value.Replace('\\','/').Split('/').LastOrDefault()??"";string clean=new string(leaf.Normalize(NormalizationForm.FormC).Where(c=>!char.IsControl(c)).ToArray()).Trim().Trim('.').Trim();if(string.IsNullOrWhiteSpace(clean))clean="attachment";return clean.Length<=255?clean:clean[..255].TrimEnd();}
    private static bool Png(Stream s,long len){if(len<45||!R(s,8).SequenceEqual(new byte[]{137,80,78,71,13,10,26,10}))return false;bool header=false,end=false;while(s.Position+12<=len){uint n=U(R(s,4));string type=Encoding.ASCII.GetString(R(s,4));if(n>len-s.Position-4||n>int.MaxValue)return false;byte[] data=R(s,(int)n);_=R(s,4);if(!header){if(type!="IHDR"||n!=13||U(data[..4])==0||U(data[4..8])==0)return false;header=true;}if(type=="IEND"){end=n==0&&s.Position==len;break;}}return header&&end;}
    private static bool Jpeg(Stream s,long len){if(len<12||!R(s,2).SequenceEqual(new byte[]{255,216}))return false;bool frame=false;while(s.Position<len){if(s.ReadByte()!=255)return false;int marker;do{marker=s.ReadByte();}while(marker==255);if(marker==217)return frame&&s.Position==len;if(marker is 1 or >=208 and <=215)continue;if(s.Position+2>len)return false;int n=BinaryPrimitives.ReadUInt16BigEndian(R(s,2));if(n<2||s.Position+n-2>len)return false;if(marker is >=192 and <=195){byte[] f=R(s,n-2);if(f.Length<5||BinaryPrimitives.ReadUInt16BigEndian(f.AsSpan(1,2))==0||BinaryPrimitives.ReadUInt16BigEndian(f.AsSpan(3,2))==0)return false;frame=true;}else{s.Position+=n-2;if(marker==218){while(s.Position<len){int b=s.ReadByte();if(b!=255)continue;int next=s.ReadByte();if(next==0||next is >=208 and <=215)continue;if(next==217)return frame&&s.Position==len;return false;}return false;}}}return false;}
    private static bool Webp(Stream s,long len){if(len<20)return false;byte[] h=R(s,12);if(Encoding.ASCII.GetString(h,0,4)!="RIFF"||Encoding.ASCII.GetString(h,8,4)!="WEBP"||BinaryPrimitives.ReadUInt32LittleEndian(h.AsSpan(4,4))+8!=len)return false;bool image=false;while(s.Position+8<=len){byte[] c=R(s,8);uint n=BinaryPrimitives.ReadUInt32LittleEndian(c.AsSpan(4,4));if(n>len-s.Position)return false;image|=Encoding.ASCII.GetString(c,0,4) is "VP8 " or "VP8L" or "VP8X";s.Position+=n+n%2;if(s.Position>len)return false;}return image&&s.Position==len;}
    private static bool Pdf(Stream s,long len){if(len<40||len>int.MaxValue)return false;string t=Encoding.Latin1.GetString(R(s,(int)len));return t.StartsWith("%PDF-",StringComparison.Ordinal)&&t.TrimEnd().EndsWith("%%EOF",StringComparison.Ordinal)&&Regex.IsMatch(t,@"\b\d+\s+\d+\s+obj\b",RegexOptions.CultureInvariant,TimeSpan.FromMilliseconds(100))&&(t.Contains("startxref",StringComparison.Ordinal)||t.Contains("/Type /Catalog",StringComparison.Ordinal));}
    private static bool Mp4(Stream s,long len){bool first=true,brand=false,payload=false;while(s.Position+8<=len){long start=s.Position;byte[] h=R(s,8);ulong size=BinaryPrimitives.ReadUInt32BigEndian(h.AsSpan(0,4));int header=8;if(size==1){if(s.Position+8>len)return false;size=BinaryPrimitives.ReadUInt64BigEndian(R(s,8));header=16;}if(size<(ulong)header||size>(ulong)(len-start))return false;long data=(long)size-header;string type=Encoding.ASCII.GetString(h,4,4);if(first){if(type!="ftyp"||data<8||data>int.MaxValue)return false;string b=Encoding.ASCII.GetString(R(s,(int)data),0,4);brand=new[]{"isom","iso2","mp41","mp42","avc1","M4V ","qt  "}.Contains(b);first=false;}else{s.Position+=data;payload|=type is "moov" or "mdat";}}return brand&&payload&&s.Position==len;}
    private static bool Text(Stream s,long len){if(len>int.MaxValue)return false;byte[] b=R(s,(int)len);if(b.Contains((byte)0))return false;try{_=new UTF8Encoding(false,true).GetString(b);return true;}catch(DecoderFallbackException){return false;}}
    private static bool Office(Stream s,string main,string contentType){if(EncryptedZip(s))return false;s.Position=0;using var z=new ZipArchive(s,ZipArchiveMode.Read,true);if(z.Entries.Count==0||z.Entries.Count>MaxEntries)return false;long total=0;ZipArchiveEntry? types=null;bool mainFound=false;foreach(ZipArchiveEntry e in z.Entries){string n=e.FullName.Replace('\\','/');if(e.Length>MaxEntry||(e.CompressedLength==0&&e.Length>0)||(e.CompressedLength>0&&(double)e.Length/e.CompressedLength>MaxRatio))return false;total+=e.Length;if(total>MaxTotal||n.Contains("../",StringComparison.Ordinal)||n.EndsWith("vbaProject.bin",StringComparison.OrdinalIgnoreCase)||new[]{".zip",".7z",".rar"}.Any(x=>n.EndsWith(x,StringComparison.OrdinalIgnoreCase)))return false;if(n.Equals("[Content_Types].xml",StringComparison.OrdinalIgnoreCase))types=e;if(n.Equals(main,StringComparison.OrdinalIgnoreCase))mainFound=true;}if(types is null||!mainFound||types.Length>MaxTypes)return false;using Stream ts=types.Open();string xml=Encoding.UTF8.GetString(ReadBounded(ts,MaxTypes));return xml.Contains(contentType,StringComparison.OrdinalIgnoreCase)&&!xml.Contains("macroEnabled",StringComparison.OrdinalIgnoreCase);}
    private static bool EncryptedZip(Stream s){if(s.Length>int.MaxValue)return true;byte[] b=R(s,(int)s.Length);for(int i=0;i+8<b.Length;i++)if(b[i]==0x50&&b[i+1]==0x4b&&b[i+2]==3&&b[i+3]==4&&(BinaryPrimitives.ReadUInt16LittleEndian(b.AsSpan(i+6,2))&1)!=0)return true;return false;}
    private static byte[] R(Stream s,int n){byte[] b=new byte[n];s.ReadExactly(b);return b;}private static uint U(ReadOnlySpan<byte>b)=>BinaryPrimitives.ReadUInt32BigEndian(b);private static byte[] ReadBounded(Stream s,int max){using var m=new MemoryStream();byte[] b=new byte[8192];while(true){int n=s.Read(b);if(n==0)break;if(m.Length+n>max)throw new InvalidDataException();m.Write(b,0,n);}return m.ToArray();}private static WorkflowException E(int status,string code,string message)=>new(status,code,message);
}
