export function MicrosoftMark() { return <span className="microsoft-mark" aria-hidden="true"><i /><i /><i /><i /></span> }

export function LoginPage({ signingIn, error, onSignIn }: { signingIn: boolean; error: string | null; onSignIn: () => void }) {
  return <main className="login-page"><div className="login-brand" aria-label="PAS AI Quest"><span>PAS</span><strong>AI QUEST</strong></div><section className="login-card" aria-labelledby="login-heading"><p className="eyebrow">PAS AI QUEST</p><h1 id="login-heading">Sign in to PAS AI Quest</h1><p>Use your company Microsoft account to continue.</p>{error && <div className="login-error" role="alert">{error}</div>}<button className="microsoft-signin" type="button" onClick={onSignIn} disabled={signingIn} aria-busy={signingIn}><MicrosoftMark /><span>{signingIn ? 'Signing in…' : 'Sign in with Microsoft'}</span></button><div className="login-guidance"><p>Access is restricted to company accounts.</p><p>Contact IT if you need access.</p></div></section><footer>CPA Australia · TDS · PAS AI Quest — internal use only</footer></main>
}

export function BrandedAuthLoading({ text = 'Restoring your secure session…' }: { text?: string }) { return <main className="login-page" aria-live="polite"><div className="login-brand"><span>PAS</span><strong>AI QUEST</strong></div><section className="login-card login-card--loading"><div className="spinner" /><h1>PAS AI Quest</h1><p>{text}</p></section></main> }

export function AccessDeniedPage({ kind, onSignOut }: { kind: 'unprovisioned' | 'forbidden'; onSignOut: () => void }) { return <main className="login-page"><div className="login-brand"><span>PAS</span><strong>AI QUEST</strong></div><section className="login-card"><p className="eyebrow">ACCESS RESTRICTED</p><h1>{kind === 'unprovisioned' ? 'PAS AI Quest access required' : 'Access denied'}</h1><p>{kind === 'unprovisioned' ? "Your Microsoft account is signed in, but you don't currently have access to PAS AI Quest." : 'Your account is authenticated, but you are not authorized to access PAS AI Quest.'}</p><p className="login-guidance">Contact IT if you believe you should have access.</p><button className="button" type="button" onClick={onSignOut}>Sign out</button></section></main> }

export function SessionErrorPage({ error, onRetry, onSignOut }: { error: string; onRetry: () => void; onSignOut: () => void }) { return <main className="login-page"><div className="login-brand"><span>PAS</span><strong>AI QUEST</strong></div><section className="login-card"><p className="eyebrow">SESSION PROBLEM</p><h1>We couldn't establish your session</h1><div className="login-error" role="alert">{error}</div><p className="login-guidance">Sign out and try again. You can retry the profile check without starting another automatic sign-in loop.</p><div className="state-actions"><button className="button button--quiet" type="button" onClick={onRetry}>Retry</button><button className="button" type="button" onClick={onSignOut}>Sign out</button></div></section></main> }
